<?php

/**
 * Profile filter form base class.
 *
 * @package    levandos
 * @subpackage filter
 * @author     Your name here
 * @version    SVN: $Id: sfDoctrineFormFilterGeneratedTemplate.php 29570 2010-05-21 14:49:47Z Kris.Wallsmith $
 */
abstract class BaseProfileFormFilter extends BaseFormFilterDoctrine
{
  public function setup()
  {
    $this->setWidgets(array(
      'user_id'                      => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('sfGuardUser'), 'add_empty' => true)),
      'first_name'                   => new sfWidgetFormFilterInput(),
      'last_name'                    => new sfWidgetFormFilterInput(),
      'middle_name'                  => new sfWidgetFormFilterInput(),
      'real_name'                    => new sfWidgetFormFilterInput(),
      'gender'                       => new sfWidgetFormChoice(array('choices' => array('' => '', 'm' => 'm', 'w' => 'w'))),
      'city'                         => new sfWidgetFormFilterInput(),
      'country'                      => new sfWidgetFormFilterInput(),
      'zip'                          => new sfWidgetFormFilterInput(),
      'adress'                       => new sfWidgetFormFilterInput(),
      'phone'                        => new sfWidgetFormFilterInput(),
      'birthday'                     => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate())),
      'height'                       => new sfWidgetFormFilterInput(),
      'body_type'                    => new sfWidgetFormFilterInput(),
      'relationship'                 => new sfWidgetFormFilterInput(),
      'rost'                         => new sfWidgetFormFilterInput(),
      'ves'                          => new sfWidgetFormFilterInput(),
      'ethnicity'                    => new sfWidgetFormFilterInput(),
      'religion'                     => new sfWidgetFormFilterInput(),
      'marital_status'               => new sfWidgetFormFilterInput(),
      'children'                     => new sfWidgetFormFilterInput(),
      'where_children'               => new sfWidgetFormFilterInput(),
      'want_children'                => new sfWidgetFormFilterInput(),
      'im'                           => new sfWidgetFormFilterInput(),
      'occupation'                   => new sfWidgetFormFilterInput(),
      'language1'                    => new sfWidgetFormFilterInput(),
      'language_skill1'              => new sfWidgetFormFilterInput(),
      'language2'                    => new sfWidgetFormFilterInput(),
      'language_skill2'              => new sfWidgetFormFilterInput(),
      'language3'                    => new sfWidgetFormFilterInput(),
      'language_skill3'              => new sfWidgetFormFilterInput(),
      'education'                    => new sfWidgetFormFilterInput(),
      'income'                       => new sfWidgetFormFilterInput(),
      'smoker'                       => new sfWidgetFormFilterInput(),
      'drinker'                      => new sfWidgetFormFilterInput(),
      'headline'                     => new sfWidgetFormFilterInput(),
      'i_can_receive'                => new sfWidgetFormFilterInput(),
      'i_look_for_a'                 => new sfWidgetFormFilterInput(),
      'looking_for_age_from'         => new sfWidgetFormFilterInput(),
      'looking_for_age_to'           => new sfWidgetFormFilterInput(),
      'looking_for_a_height_from'    => new sfWidgetFormFilterInput(),
      'looking_for_a_height_to'      => new sfWidgetFormFilterInput(),
      'looking_for_a_body_type_from' => new sfWidgetFormFilterInput(),
      'looking_for_a_body_type_to'   => new sfWidgetFormFilterInput(),
      'notify_me_about_news'         => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'mobile_phone'                 => new sfWidgetFormFilterInput(),
      'photo'                        => new sfWidgetFormFilterInput(),
      'hair_lenght'                  => new sfWidgetFormFilterInput(),
      'hair_color'                   => new sfWidgetFormFilterInput(),
      'eye_color'                    => new sfWidgetFormFilterInput(),
      'weight'                       => new sfWidgetFormFilterInput(),
      'looking_for'                  => new sfWidgetFormFilterInput(),
      'looking_for_role'             => new sfWidgetFormFilterInput(),
      'contact_lenses'               => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'is_active'                    => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'is_new_message'               => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'is_new_friend'                => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'is_new_request'               => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'is_new_gift'                  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'is_new_hotlist'               => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'is_empty'                     => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'is_online'                    => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'with_photo'                   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'with_video'                   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'subtype'                      => new sfWidgetFormChoice(array('choices' => array('' => '', 'none' => 'none', 'top100' => 'top100', 'bikini' => 'bikini'))),
      'most_active_user'             => new sfWidgetFormFilterInput(),
      'status_id'                    => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('Status'), 'add_empty' => true)),
      'homepage'                     => new sfWidgetFormFilterInput(),
      'phone2'                       => new sfWidgetFormFilterInput(),
      'icq'                          => new sfWidgetFormFilterInput(),
      'msn'                          => new sfWidgetFormFilterInput(),
      'skype'                        => new sfWidgetFormFilterInput(),
      'zodiac'                       => new sfWidgetFormFilterInput(),
      'partner_id'                   => new sfWidgetFormFilterInput(),
      'can_resive_gift'              => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'skan'                         => new sfWidgetFormFilterInput(),
      'rating'                       => new sfWidgetFormFilterInput(),
      'packet_id'                    => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('Packet'), 'add_empty' => true)),
      'max_abonent'                  => new sfWidgetFormFilterInput(),
      'cur_abonent'                  => new sfWidgetFormFilterInput(),
      'sub_newsletter'               => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'sub_fav'                      => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'sub_interest'                 => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'sub_message'                  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'cert'                         => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'scamer'                       => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'is_camera'                    => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'is_chat'                      => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'send_as_new'                  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'birthday_mark'                => new sfWidgetFormFilterInput(),
      'time_on_site'                 => new sfWidgetFormFilterInput(),
      'is_staff'                     => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'is_new'                       => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'timenew'                      => new sfWidgetFormFilterInput(),
      'ip'                           => new sfWidgetFormFilterInput(),
      'created_at'                   => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => false)),
      'updated_at'                   => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => false)),
      'object_version'               => new sfWidgetFormFilterInput(),
    ));

    $this->setValidators(array(
      'user_id'                      => new sfValidatorDoctrineChoice(array('required' => false, 'model' => $this->getRelatedModelName('sfGuardUser'), 'column' => 'id')),
      'first_name'                   => new sfValidatorPass(array('required' => false)),
      'last_name'                    => new sfValidatorPass(array('required' => false)),
      'middle_name'                  => new sfValidatorPass(array('required' => false)),
      'real_name'                    => new sfValidatorPass(array('required' => false)),
      'gender'                       => new sfValidatorChoice(array('required' => false, 'choices' => array('m' => 'm', 'w' => 'w'))),
      'city'                         => new sfValidatorPass(array('required' => false)),
      'country'                      => new sfValidatorPass(array('required' => false)),
      'zip'                          => new sfValidatorPass(array('required' => false)),
      'adress'                       => new sfValidatorPass(array('required' => false)),
      'phone'                        => new sfValidatorPass(array('required' => false)),
      'birthday'                     => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDate(array('required' => false)), 'to_date' => new sfValidatorDateTime(array('required' => false)))),
      'height'                       => new sfValidatorPass(array('required' => false)),
      'body_type'                    => new sfValidatorPass(array('required' => false)),
      'relationship'                 => new sfValidatorPass(array('required' => false)),
      'rost'                         => new sfValidatorPass(array('required' => false)),
      'ves'                          => new sfValidatorPass(array('required' => false)),
      'ethnicity'                    => new sfValidatorPass(array('required' => false)),
      'religion'                     => new sfValidatorPass(array('required' => false)),
      'marital_status'               => new sfValidatorPass(array('required' => false)),
      'children'                     => new sfValidatorPass(array('required' => false)),
      'where_children'               => new sfValidatorPass(array('required' => false)),
      'want_children'                => new sfValidatorPass(array('required' => false)),
      'im'                           => new sfValidatorPass(array('required' => false)),
      'occupation'                   => new sfValidatorPass(array('required' => false)),
      'language1'                    => new sfValidatorPass(array('required' => false)),
      'language_skill1'              => new sfValidatorPass(array('required' => false)),
      'language2'                    => new sfValidatorPass(array('required' => false)),
      'language_skill2'              => new sfValidatorPass(array('required' => false)),
      'language3'                    => new sfValidatorPass(array('required' => false)),
      'language_skill3'              => new sfValidatorPass(array('required' => false)),
      'education'                    => new sfValidatorPass(array('required' => false)),
      'income'                       => new sfValidatorPass(array('required' => false)),
      'smoker'                       => new sfValidatorPass(array('required' => false)),
      'drinker'                      => new sfValidatorPass(array('required' => false)),
      'headline'                     => new sfValidatorPass(array('required' => false)),
      'i_can_receive'                => new sfValidatorPass(array('required' => false)),
      'i_look_for_a'                 => new sfValidatorPass(array('required' => false)),
      'looking_for_age_from'         => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'looking_for_age_to'           => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'looking_for_a_height_from'    => new sfValidatorPass(array('required' => false)),
      'looking_for_a_height_to'      => new sfValidatorPass(array('required' => false)),
      'looking_for_a_body_type_from' => new sfValidatorPass(array('required' => false)),
      'looking_for_a_body_type_to'   => new sfValidatorPass(array('required' => false)),
      'notify_me_about_news'         => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'mobile_phone'                 => new sfValidatorPass(array('required' => false)),
      'photo'                        => new sfValidatorPass(array('required' => false)),
      'hair_lenght'                  => new sfValidatorPass(array('required' => false)),
      'hair_color'                   => new sfValidatorPass(array('required' => false)),
      'eye_color'                    => new sfValidatorPass(array('required' => false)),
      'weight'                       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'looking_for'                  => new sfValidatorPass(array('required' => false)),
      'looking_for_role'             => new sfValidatorPass(array('required' => false)),
      'contact_lenses'               => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'is_active'                    => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'is_new_message'               => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'is_new_friend'                => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'is_new_request'               => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'is_new_gift'                  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'is_new_hotlist'               => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'is_empty'                     => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'is_online'                    => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'with_photo'                   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'with_video'                   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'subtype'                      => new sfValidatorChoice(array('required' => false, 'choices' => array('none' => 'none', 'top100' => 'top100', 'bikini' => 'bikini'))),
      'most_active_user'             => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'status_id'                    => new sfValidatorDoctrineChoice(array('required' => false, 'model' => $this->getRelatedModelName('Status'), 'column' => 'id')),
      'homepage'                     => new sfValidatorPass(array('required' => false)),
      'phone2'                       => new sfValidatorPass(array('required' => false)),
      'icq'                          => new sfValidatorPass(array('required' => false)),
      'msn'                          => new sfValidatorPass(array('required' => false)),
      'skype'                        => new sfValidatorPass(array('required' => false)),
      'zodiac'                       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'partner_id'                   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'can_resive_gift'              => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'skan'                         => new sfValidatorPass(array('required' => false)),
      'rating'                       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'packet_id'                    => new sfValidatorDoctrineChoice(array('required' => false, 'model' => $this->getRelatedModelName('Packet'), 'column' => 'id')),
      'max_abonent'                  => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'cur_abonent'                  => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'sub_newsletter'               => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'sub_fav'                      => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'sub_interest'                 => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'sub_message'                  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'cert'                         => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'scamer'                       => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'is_camera'                    => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'is_chat'                      => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'send_as_new'                  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'birthday_mark'                => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'time_on_site'                 => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'is_staff'                     => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'is_new'                       => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'timenew'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'ip'                           => new sfValidatorPass(array('required' => false)),
      'created_at'                   => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 00:00:00')), 'to_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 23:59:59')))),
      'updated_at'                   => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 00:00:00')), 'to_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 23:59:59')))),
      'object_version'               => new sfValidatorPass(array('required' => false)),
    ));

    $this->widgetSchema->setNameFormat('profile_filters[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    $this->setupInheritance();

    parent::setup();
  }

  public function getModelName()
  {
    return 'Profile';
  }

  public function getFields()
  {
    return array(
      'id'                           => 'Number',
      'user_id'                      => 'ForeignKey',
      'first_name'                   => 'Text',
      'last_name'                    => 'Text',
      'middle_name'                  => 'Text',
      'real_name'                    => 'Text',
      'gender'                       => 'Enum',
      'city'                         => 'Text',
      'country'                      => 'Text',
      'zip'                          => 'Text',
      'adress'                       => 'Text',
      'phone'                        => 'Text',
      'birthday'                     => 'Date',
      'height'                       => 'Text',
      'body_type'                    => 'Text',
      'relationship'                 => 'Text',
      'rost'                         => 'Text',
      'ves'                          => 'Text',
      'ethnicity'                    => 'Text',
      'religion'                     => 'Text',
      'marital_status'               => 'Text',
      'children'                     => 'Text',
      'where_children'               => 'Text',
      'want_children'                => 'Text',
      'im'                           => 'Text',
      'occupation'                   => 'Text',
      'language1'                    => 'Text',
      'language_skill1'              => 'Text',
      'language2'                    => 'Text',
      'language_skill2'              => 'Text',
      'language3'                    => 'Text',
      'language_skill3'              => 'Text',
      'education'                    => 'Text',
      'income'                       => 'Text',
      'smoker'                       => 'Text',
      'drinker'                      => 'Text',
      'headline'                     => 'Text',
      'i_can_receive'                => 'Text',
      'i_look_for_a'                 => 'Text',
      'looking_for_age_from'         => 'Number',
      'looking_for_age_to'           => 'Number',
      'looking_for_a_height_from'    => 'Text',
      'looking_for_a_height_to'      => 'Text',
      'looking_for_a_body_type_from' => 'Text',
      'looking_for_a_body_type_to'   => 'Text',
      'notify_me_about_news'         => 'Boolean',
      'mobile_phone'                 => 'Text',
      'photo'                        => 'Text',
      'hair_lenght'                  => 'Text',
      'hair_color'                   => 'Text',
      'eye_color'                    => 'Text',
      'weight'                       => 'Number',
      'looking_for'                  => 'Text',
      'looking_for_role'             => 'Text',
      'contact_lenses'               => 'Boolean',
      'is_active'                    => 'Boolean',
      'is_new_message'               => 'Boolean',
      'is_new_friend'                => 'Boolean',
      'is_new_request'               => 'Boolean',
      'is_new_gift'                  => 'Boolean',
      'is_new_hotlist'               => 'Boolean',
      'is_empty'                     => 'Boolean',
      'is_online'                    => 'Boolean',
      'with_photo'                   => 'Boolean',
      'with_video'                   => 'Boolean',
      'subtype'                      => 'Enum',
      'most_active_user'             => 'Number',
      'status_id'                    => 'ForeignKey',
      'homepage'                     => 'Text',
      'phone2'                       => 'Text',
      'icq'                          => 'Text',
      'msn'                          => 'Text',
      'skype'                        => 'Text',
      'zodiac'                       => 'Number',
      'partner_id'                   => 'Number',
      'can_resive_gift'              => 'Boolean',
      'skan'                         => 'Text',
      'rating'                       => 'Number',
      'packet_id'                    => 'ForeignKey',
      'max_abonent'                  => 'Number',
      'cur_abonent'                  => 'Number',
      'sub_newsletter'               => 'Boolean',
      'sub_fav'                      => 'Boolean',
      'sub_interest'                 => 'Boolean',
      'sub_message'                  => 'Boolean',
      'cert'                         => 'Boolean',
      'scamer'                       => 'Boolean',
      'is_camera'                    => 'Boolean',
      'is_chat'                      => 'Boolean',
      'send_as_new'                  => 'Boolean',
      'birthday_mark'                => 'Number',
      'time_on_site'                 => 'Number',
      'is_staff'                     => 'Boolean',
      'is_new'                       => 'Boolean',
      'timenew'                      => 'Number',
      'ip'                           => 'Text',
      'created_at'                   => 'Date',
      'updated_at'                   => 'Date',
      'object_version'               => 'Text',
    );
  }
}
