<?php

/**
 * BaseChat2VideoLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $time_start
 * @property integer $time_end
 * @property integer $delta
 * @property integer $room_id
 * @property integer $user_id
 * @property Chat2Room $Room
 * @property sfGuardUser $User
 * 
 * @method integer       getId()         Returns the current record's "id" value
 * @method integer       getTimeStart()  Returns the current record's "time_start" value
 * @method integer       getTimeEnd()    Returns the current record's "time_end" value
 * @method integer       getDelta()      Returns the current record's "delta" value
 * @method integer       getRoomId()     Returns the current record's "room_id" value
 * @method integer       getUserId()     Returns the current record's "user_id" value
 * @method Chat2Room     getRoom()       Returns the current record's "Room" value
 * @method sfGuardUser   getUser()       Returns the current record's "User" value
 * @method Chat2VideoLog setId()         Sets the current record's "id" value
 * @method Chat2VideoLog setTimeStart()  Sets the current record's "time_start" value
 * @method Chat2VideoLog setTimeEnd()    Sets the current record's "time_end" value
 * @method Chat2VideoLog setDelta()      Sets the current record's "delta" value
 * @method Chat2VideoLog setRoomId()     Sets the current record's "room_id" value
 * @method Chat2VideoLog setUserId()     Sets the current record's "user_id" value
 * @method Chat2VideoLog setRoom()       Sets the current record's "Room" value
 * @method Chat2VideoLog setUser()       Sets the current record's "User" value
 * 
 * @package    levandos
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseChat2VideoLog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('jo_chat2_videolog');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('time_start', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('time_end', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('delta', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('room_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Chat2Room as Room', array(
             'local' => 'room_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}