<?php

/**
 * BaseMyCity
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $country
 * @property string $city
 * @property string $content
 * @property string $image1
 * @property string $image2
 * @property string $image3
 * @property string $image4
 * @property string $image5
 * @property boolean $pub
 * 
 * @method integer getId()      Returns the current record's "id" value
 * @method string  getCountry() Returns the current record's "country" value
 * @method string  getCity()    Returns the current record's "city" value
 * @method string  getContent() Returns the current record's "content" value
 * @method string  getImage1()  Returns the current record's "image1" value
 * @method string  getImage2()  Returns the current record's "image2" value
 * @method string  getImage3()  Returns the current record's "image3" value
 * @method string  getImage4()  Returns the current record's "image4" value
 * @method string  getImage5()  Returns the current record's "image5" value
 * @method boolean getPub()     Returns the current record's "pub" value
 * @method MyCity  setId()      Sets the current record's "id" value
 * @method MyCity  setCountry() Sets the current record's "country" value
 * @method MyCity  setCity()    Sets the current record's "city" value
 * @method MyCity  setContent() Sets the current record's "content" value
 * @method MyCity  setImage1()  Sets the current record's "image1" value
 * @method MyCity  setImage2()  Sets the current record's "image2" value
 * @method MyCity  setImage3()  Sets the current record's "image3" value
 * @method MyCity  setImage4()  Sets the current record's "image4" value
 * @method MyCity  setImage5()  Sets the current record's "image5" value
 * @method MyCity  setPub()     Sets the current record's "pub" value
 * 
 * @package    levandos
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMyCity extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('my_city');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('country', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('city', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('content', 'string', 250000, array(
             'type' => 'string',
             'length' => 250000,
             ));
        $this->hasColumn('image1', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('image2', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('image3', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('image4', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('image5', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('pub', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'content',
              1 => 'country',
              2 => 'city',
             ),
             ));
        $this->actAs($i18n0);
    }
}