<?php

/**
 * BaseActions
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $description
 * @property integer $type_actions_id
 * @property integer $user_id
 * @property integer $group_id
 * @property TypeActions $TypeKeywords
 * @property sfGuardUser $User
 * 
 * @method integer     getId()              Returns the current record's "id" value
 * @method string      getDescription()     Returns the current record's "description" value
 * @method integer     getTypeActionsId()   Returns the current record's "type_actions_id" value
 * @method integer     getUserId()          Returns the current record's "user_id" value
 * @method integer     getGroupId()         Returns the current record's "group_id" value
 * @method TypeActions getTypeKeywords()    Returns the current record's "TypeKeywords" value
 * @method sfGuardUser getUser()            Returns the current record's "User" value
 * @method Actions     setId()              Sets the current record's "id" value
 * @method Actions     setDescription()     Sets the current record's "description" value
 * @method Actions     setTypeActionsId()   Sets the current record's "type_actions_id" value
 * @method Actions     setUserId()          Sets the current record's "user_id" value
 * @method Actions     setGroupId()         Sets the current record's "group_id" value
 * @method Actions     setTypeKeywords()    Sets the current record's "TypeKeywords" value
 * @method Actions     setUser()            Sets the current record's "User" value
 * 
 * @package    levandos
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseActions extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('jo_actions');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('description', 'string', 25000, array(
             'type' => 'string',
             'length' => 25000,
             ));
        $this->hasColumn('type_actions_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('group_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TypeActions as TypeKeywords', array(
             'local' => 'type_actions_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}