<?php

/**
 * BaseLiqpay
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $out_xml
 * @property string $in_xml
 * @property integer $status
 * @property integer $summa
 * @property string $description
 * @property integer $user_id
 * @property integer $ammount
 * @property integer $membership_id
 * @property sfGuardUser $User
 * 
 * @method integer     getId()            Returns the current record's "id" value
 * @method string      getOutXml()        Returns the current record's "out_xml" value
 * @method string      getInXml()         Returns the current record's "in_xml" value
 * @method integer     getStatus()        Returns the current record's "status" value
 * @method integer     getSumma()         Returns the current record's "summa" value
 * @method string      getDescription()   Returns the current record's "description" value
 * @method integer     getUserId()        Returns the current record's "user_id" value
 * @method integer     getAmmount()       Returns the current record's "ammount" value
 * @method integer     getMembershipId()  Returns the current record's "membership_id" value
 * @method sfGuardUser getUser()          Returns the current record's "User" value
 * @method Liqpay      setId()            Sets the current record's "id" value
 * @method Liqpay      setOutXml()        Sets the current record's "out_xml" value
 * @method Liqpay      setInXml()         Sets the current record's "in_xml" value
 * @method Liqpay      setStatus()        Sets the current record's "status" value
 * @method Liqpay      setSumma()         Sets the current record's "summa" value
 * @method Liqpay      setDescription()   Sets the current record's "description" value
 * @method Liqpay      setUserId()        Sets the current record's "user_id" value
 * @method Liqpay      setAmmount()       Sets the current record's "ammount" value
 * @method Liqpay      setMembershipId()  Sets the current record's "membership_id" value
 * @method Liqpay      setUser()          Sets the current record's "User" value
 * 
 * @package    levandos
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLiqpay extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('liqpay');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('out_xml', 'string', 25000, array(
             'type' => 'string',
             'length' => 25000,
             ));
        $this->hasColumn('in_xml', 'string', 25000, array(
             'type' => 'string',
             'length' => 25000,
             ));
        $this->hasColumn('status', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('summa', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('description', 'string', 25000, array(
             'type' => 'string',
             'length' => 25000,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ammount', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('membership_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}