<?php

/**
 * BaseChat2Chanels
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $girl_src
 * @property string $user_src
 * @property integer $user_id
 * @property integer $last_active
 * @property string $host
 * 
 * @method integer      getId()          Returns the current record's "id" value
 * @method string       getGirlSrc()     Returns the current record's "girl_src" value
 * @method string       getUserSrc()     Returns the current record's "user_src" value
 * @method integer      getUserId()      Returns the current record's "user_id" value
 * @method integer      getLastActive()  Returns the current record's "last_active" value
 * @method string       getHost()        Returns the current record's "host" value
 * @method Chat2Chanels setId()          Sets the current record's "id" value
 * @method Chat2Chanels setGirlSrc()     Sets the current record's "girl_src" value
 * @method Chat2Chanels setUserSrc()     Sets the current record's "user_src" value
 * @method Chat2Chanels setUserId()      Sets the current record's "user_id" value
 * @method Chat2Chanels setLastActive()  Sets the current record's "last_active" value
 * @method Chat2Chanels setHost()        Sets the current record's "host" value
 * 
 * @package    levandos
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseChat2Chanels extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('jo_chat2_chanels');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('girl_src', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('user_src', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('last_active', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('host', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}