<?php

/**
 * BaseBlacklist
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property integer $black_id
 * @property sfGuardUser $User
 * @property sfGuardUser $Black
 * 
 * @method integer     getId()       Returns the current record's "id" value
 * @method integer     getUserId()   Returns the current record's "user_id" value
 * @method integer     getBlackId()  Returns the current record's "black_id" value
 * @method sfGuardUser getUser()     Returns the current record's "User" value
 * @method sfGuardUser getBlack()    Returns the current record's "Black" value
 * @method Blacklist   setId()       Sets the current record's "id" value
 * @method Blacklist   setUserId()   Sets the current record's "user_id" value
 * @method Blacklist   setBlackId()  Sets the current record's "black_id" value
 * @method Blacklist   setUser()     Sets the current record's "User" value
 * @method Blacklist   setBlack()    Sets the current record's "Black" value
 * 
 * @package    levandos
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBlacklist extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('jo_blacklist');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('black_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser as Black', array(
             'local' => 'black_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}