<?php

/**
 * BaseSettings
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $var_name
 * @property string $var_value
 * @property string $var_description
 * @property boolean $pub
 * 
 * @method string   getVarName()         Returns the current record's "var_name" value
 * @method string   getVarValue()        Returns the current record's "var_value" value
 * @method string   getVarDescription()  Returns the current record's "var_description" value
 * @method boolean  getPub()             Returns the current record's "pub" value
 * @method Settings setVarName()         Sets the current record's "var_name" value
 * @method Settings setVarValue()        Sets the current record's "var_value" value
 * @method Settings setVarDescription()  Sets the current record's "var_description" value
 * @method Settings setPub()             Sets the current record's "pub" value
 * 
 * @package    levandos
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSettings extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('jo_settings');
        $this->hasColumn('var_name', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('var_value', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('var_description', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('pub', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}