<?php

/**
 * BaseContact
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $body
 * @property string $image
 * @property string $name
 * @property boolean $pub
 * 
 * @method integer getId()    Returns the current record's "id" value
 * @method string  getBody()  Returns the current record's "body" value
 * @method string  getImage() Returns the current record's "image" value
 * @method string  getName()  Returns the current record's "name" value
 * @method boolean getPub()   Returns the current record's "pub" value
 * @method Contact setId()    Sets the current record's "id" value
 * @method Contact setBody()  Sets the current record's "body" value
 * @method Contact setImage() Sets the current record's "image" value
 * @method Contact setName()  Sets the current record's "name" value
 * @method Contact setPub()   Sets the current record's "pub" value
 * 
 * @package    levandos
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContact extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('jo_contact');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('body', 'string', 2500, array(
             'type' => 'string',
             'length' => 2500,
             ));
        $this->hasColumn('image', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('name', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('pub', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}