<?php

/**
 * BaseInterest
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property integer $interest_id
 * @property boolean $is_read_user
 * @property boolean $is_read_interest
 * @property boolean $popup
 * @property sfGuardUser $User
 * @property sfGuardUser $Interest
 * 
 * @method integer     getId()               Returns the current record's "id" value
 * @method integer     getUserId()           Returns the current record's "user_id" value
 * @method integer     getInterestId()       Returns the current record's "interest_id" value
 * @method boolean     getIsReadUser()       Returns the current record's "is_read_user" value
 * @method boolean     getIsReadInterest()   Returns the current record's "is_read_interest" value
 * @method boolean     getPopup()            Returns the current record's "popup" value
 * @method sfGuardUser getUser()             Returns the current record's "User" value
 * @method sfGuardUser getInterest()         Returns the current record's "Interest" value
 * @method Interest    setId()               Sets the current record's "id" value
 * @method Interest    setUserId()           Sets the current record's "user_id" value
 * @method Interest    setInterestId()       Sets the current record's "interest_id" value
 * @method Interest    setIsReadUser()       Sets the current record's "is_read_user" value
 * @method Interest    setIsReadInterest()   Sets the current record's "is_read_interest" value
 * @method Interest    setPopup()            Sets the current record's "popup" value
 * @method Interest    setUser()             Sets the current record's "User" value
 * @method Interest    setInterest()         Sets the current record's "Interest" value
 * 
 * @package    levandos
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseInterest extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('jo_interest');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('interest_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('is_read_user', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('is_read_interest', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('popup', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser as Interest', array(
             'local' => 'interest_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}