<?php

/**
 * BaseChatAppointment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $man_id
 * @property integer $girl_id
 * @property timestamp $date
 * @property integer $timer
 * @property integer $status
 * @property sfGuardUser $Man
 * @property sfGuardUser $Girl
 * 
 * @method integer         getId()      Returns the current record's "id" value
 * @method integer         getManId()   Returns the current record's "man_id" value
 * @method integer         getGirlId()  Returns the current record's "girl_id" value
 * @method timestamp       getDate()    Returns the current record's "date" value
 * @method integer         getTimer()   Returns the current record's "timer" value
 * @method integer         getStatus()  Returns the current record's "status" value
 * @method sfGuardUser     getMan()     Returns the current record's "Man" value
 * @method sfGuardUser     getGirl()    Returns the current record's "Girl" value
 * @method ChatAppointment setId()      Sets the current record's "id" value
 * @method ChatAppointment setManId()   Sets the current record's "man_id" value
 * @method ChatAppointment setGirlId()  Sets the current record's "girl_id" value
 * @method ChatAppointment setDate()    Sets the current record's "date" value
 * @method ChatAppointment setTimer()   Sets the current record's "timer" value
 * @method ChatAppointment setStatus()  Sets the current record's "status" value
 * @method ChatAppointment setMan()     Sets the current record's "Man" value
 * @method ChatAppointment setGirl()    Sets the current record's "Girl" value
 * 
 * @package    levandos
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseChatAppointment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('chat_appointment');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('man_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('girl_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('timer', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('status', 'integer', 1, array(
             'type' => 'integer',
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as Man', array(
             'local' => 'man_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser as Girl', array(
             'local' => 'girl_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}