<?php

/**
 * BasePage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $alias
 * @property string $title
 * @property string $icontent
 * @property string $ititle
 * @property boolean $undel
 * 
 * @method integer getId()       Returns the current record's "id" value
 * @method string  getAlias()    Returns the current record's "alias" value
 * @method string  getTitle()    Returns the current record's "title" value
 * @method string  getIcontent() Returns the current record's "icontent" value
 * @method string  getItitle()   Returns the current record's "ititle" value
 * @method boolean getUndel()    Returns the current record's "undel" value
 * @method Page    setId()       Sets the current record's "id" value
 * @method Page    setAlias()    Sets the current record's "alias" value
 * @method Page    setTitle()    Sets the current record's "title" value
 * @method Page    setIcontent() Sets the current record's "icontent" value
 * @method Page    setItitle()   Sets the current record's "ititle" value
 * @method Page    setUndel()    Sets the current record's "undel" value
 * 
 * @package    levandos
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('jo_page');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('alias', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('title', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('icontent', 'string', 1000000, array(
             'type' => 'string',
             'length' => 1000000,
             ));
        $this->hasColumn('ititle', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('undel', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'icontent',
              1 => 'ititle',
             ),
             ));
        $this->actAs($i18n0);
    }
}