<?php

/**
 * BaseProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property string $first_name
 * @property string $last_name
 * @property string $ifirst_name
 * @property string $ilast_name
 * @property string $middle_name
 * @property string $real_name
 * @property enum $gender
 * @property string $city
 * @property string $icity
 * @property string $country
 * @property string $zip
 * @property string $adress
 * @property string $phone
 * @property date $birthday
 * @property string $height
 * @property string $body_type
 * @property string $relationship
 * @property string $rost
 * @property string $ves
 * @property string $ethnicity
 * @property string $religion
 * @property string $marital_status
 * @property string $children
 * @property string $where_children
 * @property string $want_children
 * @property string $im
 * @property string $occupation
 * @property string $ioccupation
 * @property string $language1
 * @property string $language_skill1
 * @property string $language2
 * @property string $language_skill2
 * @property string $language3
 * @property string $language_skill3
 * @property string $education
 * @property string $income
 * @property string $smoker
 * @property string $drinker
 * @property string $headline
 * @property string $description
 * @property string $i_can_receive
 * @property string $i_look_for_a
 * @property integer $looking_for_age_from
 * @property integer $looking_for_age_to
 * @property string $looking_for_a_height_from
 * @property string $looking_for_a_height_to
 * @property string $looking_for_a_body_type_from
 * @property string $looking_for_a_body_type_to
 * @property string $ideal_match_description
 * @property boolean $notify_me_about_news
 * @property string $mobile_phone
 * @property string $photo
 * @property string $hair_lenght
 * @property string $hair_color
 * @property string $eye_color
 * @property string $hobbies
 * @property integer $weight
 * @property string $looking_for
 * @property string $looking_for_role
 * @property boolean $contact_lenses
 * @property boolean $is_active
 * @property boolean $is_new_message
 * @property boolean $is_new_friend
 * @property boolean $is_new_request
 * @property boolean $is_new_gift
 * @property boolean $is_new_hotlist
 * @property boolean $is_empty
 * @property boolean $is_online
 * @property boolean $with_photo
 * @property boolean $with_video
 * @property enum $subtype
 * @property integer $most_active_user
 * @property integer $status_id
 * @property string $homepage
 * @property string $phone2
 * @property string $icq
 * @property string $msn
 * @property string $skype
 * @property integer $zodiac
 * @property integer $partner_id
 * @property boolean $can_resive_gift
 * @property string $skan
 * @property integer $rating
 * @property integer $packet_id
 * @property integer $max_abonent
 * @property integer $cur_abonent
 * @property boolean $sub_newsletter
 * @property boolean $sub_fav
 * @property boolean $sub_interest
 * @property boolean $sub_message
 * @property boolean $cert
 * @property boolean $scamer
 * @property boolean $is_camera
 * @property boolean $is_chat
 * @property boolean $send_as_new
 * @property integer $birthday_mark
 * @property integer $time_on_site
 * @property boolean $is_staff
 * @property boolean $is_new
 * @property integer $timenew
 * @property string $ip
 * @property sfGuardUser $sfGuardUser
 * @property ProfileType $Status
 * @property ProfilePacket $Packet
 * 
 * @method integer       getUserId()                       Returns the current record's "user_id" value
 * @method string        getFirstName()                    Returns the current record's "first_name" value
 * @method string        getLastName()                     Returns the current record's "last_name" value
 * @method string        getIfirstName()                   Returns the current record's "ifirst_name" value
 * @method string        getIlastName()                    Returns the current record's "ilast_name" value
 * @method string        getMiddleName()                   Returns the current record's "middle_name" value
 * @method string        getRealName()                     Returns the current record's "real_name" value
 * @method enum          getGender()                       Returns the current record's "gender" value
 * @method string        getCity()                         Returns the current record's "city" value
 * @method string        getIcity()                        Returns the current record's "icity" value
 * @method string        getCountry()                      Returns the current record's "country" value
 * @method string        getZip()                          Returns the current record's "zip" value
 * @method string        getAdress()                       Returns the current record's "adress" value
 * @method string        getPhone()                        Returns the current record's "phone" value
 * @method date          getBirthday()                     Returns the current record's "birthday" value
 * @method string        getHeight()                       Returns the current record's "height" value
 * @method string        getBodyType()                     Returns the current record's "body_type" value
 * @method string        getRelationship()                 Returns the current record's "relationship" value
 * @method string        getRost()                         Returns the current record's "rost" value
 * @method string        getVes()                          Returns the current record's "ves" value
 * @method string        getEthnicity()                    Returns the current record's "ethnicity" value
 * @method string        getReligion()                     Returns the current record's "religion" value
 * @method string        getMaritalStatus()                Returns the current record's "marital_status" value
 * @method string        getChildren()                     Returns the current record's "children" value
 * @method string        getWhereChildren()                Returns the current record's "where_children" value
 * @method string        getWantChildren()                 Returns the current record's "want_children" value
 * @method string        getIm()                           Returns the current record's "im" value
 * @method string        getOccupation()                   Returns the current record's "occupation" value
 * @method string        getIoccupation()                  Returns the current record's "ioccupation" value
 * @method string        getLanguage1()                    Returns the current record's "language1" value
 * @method string        getLanguageSkill1()               Returns the current record's "language_skill1" value
 * @method string        getLanguage2()                    Returns the current record's "language2" value
 * @method string        getLanguageSkill2()               Returns the current record's "language_skill2" value
 * @method string        getLanguage3()                    Returns the current record's "language3" value
 * @method string        getLanguageSkill3()               Returns the current record's "language_skill3" value
 * @method string        getEducation()                    Returns the current record's "education" value
 * @method string        getIncome()                       Returns the current record's "income" value
 * @method string        getSmoker()                       Returns the current record's "smoker" value
 * @method string        getDrinker()                      Returns the current record's "drinker" value
 * @method string        getHeadline()                     Returns the current record's "headline" value
 * @method string        getDescription()                  Returns the current record's "description" value
 * @method string        getICanReceive()                  Returns the current record's "i_can_receive" value
 * @method string        getILookForA()                    Returns the current record's "i_look_for_a" value
 * @method integer       getLookingForAgeFrom()            Returns the current record's "looking_for_age_from" value
 * @method integer       getLookingForAgeTo()              Returns the current record's "looking_for_age_to" value
 * @method string        getLookingForAHeightFrom()        Returns the current record's "looking_for_a_height_from" value
 * @method string        getLookingForAHeightTo()          Returns the current record's "looking_for_a_height_to" value
 * @method string        getLookingForABodyTypeFrom()      Returns the current record's "looking_for_a_body_type_from" value
 * @method string        getLookingForABodyTypeTo()        Returns the current record's "looking_for_a_body_type_to" value
 * @method string        getIdealMatchDescription()        Returns the current record's "ideal_match_description" value
 * @method boolean       getNotifyMeAboutNews()            Returns the current record's "notify_me_about_news" value
 * @method string        getMobilePhone()                  Returns the current record's "mobile_phone" value
 * @method string        getPhoto()                        Returns the current record's "photo" value
 * @method string        getHairLenght()                   Returns the current record's "hair_lenght" value
 * @method string        getHairColor()                    Returns the current record's "hair_color" value
 * @method string        getEyeColor()                     Returns the current record's "eye_color" value
 * @method string        getHobbies()                      Returns the current record's "hobbies" value
 * @method integer       getWeight()                       Returns the current record's "weight" value
 * @method string        getLookingFor()                   Returns the current record's "looking_for" value
 * @method string        getLookingForRole()               Returns the current record's "looking_for_role" value
 * @method boolean       getContactLenses()                Returns the current record's "contact_lenses" value
 * @method boolean       getIsActive()                     Returns the current record's "is_active" value
 * @method boolean       getIsNewMessage()                 Returns the current record's "is_new_message" value
 * @method boolean       getIsNewFriend()                  Returns the current record's "is_new_friend" value
 * @method boolean       getIsNewRequest()                 Returns the current record's "is_new_request" value
 * @method boolean       getIsNewGift()                    Returns the current record's "is_new_gift" value
 * @method boolean       getIsNewHotlist()                 Returns the current record's "is_new_hotlist" value
 * @method boolean       getIsEmpty()                      Returns the current record's "is_empty" value
 * @method boolean       getIsOnline()                     Returns the current record's "is_online" value
 * @method boolean       getWithPhoto()                    Returns the current record's "with_photo" value
 * @method boolean       getWithVideo()                    Returns the current record's "with_video" value
 * @method enum          getSubtype()                      Returns the current record's "subtype" value
 * @method integer       getMostActiveUser()               Returns the current record's "most_active_user" value
 * @method integer       getStatusId()                     Returns the current record's "status_id" value
 * @method string        getHomepage()                     Returns the current record's "homepage" value
 * @method string        getPhone2()                       Returns the current record's "phone2" value
 * @method string        getIcq()                          Returns the current record's "icq" value
 * @method string        getMsn()                          Returns the current record's "msn" value
 * @method string        getSkype()                        Returns the current record's "skype" value
 * @method integer       getZodiac()                       Returns the current record's "zodiac" value
 * @method integer       getPartnerId()                    Returns the current record's "partner_id" value
 * @method boolean       getCanResiveGift()                Returns the current record's "can_resive_gift" value
 * @method string        getSkan()                         Returns the current record's "skan" value
 * @method integer       getRating()                       Returns the current record's "rating" value
 * @method integer       getPacketId()                     Returns the current record's "packet_id" value
 * @method integer       getMaxAbonent()                   Returns the current record's "max_abonent" value
 * @method integer       getCurAbonent()                   Returns the current record's "cur_abonent" value
 * @method boolean       getSubNewsletter()                Returns the current record's "sub_newsletter" value
 * @method boolean       getSubFav()                       Returns the current record's "sub_fav" value
 * @method boolean       getSubInterest()                  Returns the current record's "sub_interest" value
 * @method boolean       getSubMessage()                   Returns the current record's "sub_message" value
 * @method boolean       getCert()                         Returns the current record's "cert" value
 * @method boolean       getScamer()                       Returns the current record's "scamer" value
 * @method boolean       getIsCamera()                     Returns the current record's "is_camera" value
 * @method boolean       getIsChat()                       Returns the current record's "is_chat" value
 * @method boolean       getSendAsNew()                    Returns the current record's "send_as_new" value
 * @method integer       getBirthdayMark()                 Returns the current record's "birthday_mark" value
 * @method integer       getTimeOnSite()                   Returns the current record's "time_on_site" value
 * @method boolean       getIsStaff()                      Returns the current record's "is_staff" value
 * @method boolean       getIsNew()                        Returns the current record's "is_new" value
 * @method integer       getTimenew()                      Returns the current record's "timenew" value
 * @method string        getIp()                           Returns the current record's "ip" value
 * @method sfGuardUser   getSfGuardUser()                  Returns the current record's "sfGuardUser" value
 * @method ProfileType   getStatus()                       Returns the current record's "Status" value
 * @method ProfilePacket getPacket()                       Returns the current record's "Packet" value
 * @method Profile       setUserId()                       Sets the current record's "user_id" value
 * @method Profile       setFirstName()                    Sets the current record's "first_name" value
 * @method Profile       setLastName()                     Sets the current record's "last_name" value
 * @method Profile       setIfirstName()                   Sets the current record's "ifirst_name" value
 * @method Profile       setIlastName()                    Sets the current record's "ilast_name" value
 * @method Profile       setMiddleName()                   Sets the current record's "middle_name" value
 * @method Profile       setRealName()                     Sets the current record's "real_name" value
 * @method Profile       setGender()                       Sets the current record's "gender" value
 * @method Profile       setCity()                         Sets the current record's "city" value
 * @method Profile       setIcity()                        Sets the current record's "icity" value
 * @method Profile       setCountry()                      Sets the current record's "country" value
 * @method Profile       setZip()                          Sets the current record's "zip" value
 * @method Profile       setAdress()                       Sets the current record's "adress" value
 * @method Profile       setPhone()                        Sets the current record's "phone" value
 * @method Profile       setBirthday()                     Sets the current record's "birthday" value
 * @method Profile       setHeight()                       Sets the current record's "height" value
 * @method Profile       setBodyType()                     Sets the current record's "body_type" value
 * @method Profile       setRelationship()                 Sets the current record's "relationship" value
 * @method Profile       setRost()                         Sets the current record's "rost" value
 * @method Profile       setVes()                          Sets the current record's "ves" value
 * @method Profile       setEthnicity()                    Sets the current record's "ethnicity" value
 * @method Profile       setReligion()                     Sets the current record's "religion" value
 * @method Profile       setMaritalStatus()                Sets the current record's "marital_status" value
 * @method Profile       setChildren()                     Sets the current record's "children" value
 * @method Profile       setWhereChildren()                Sets the current record's "where_children" value
 * @method Profile       setWantChildren()                 Sets the current record's "want_children" value
 * @method Profile       setIm()                           Sets the current record's "im" value
 * @method Profile       setOccupation()                   Sets the current record's "occupation" value
 * @method Profile       setIoccupation()                  Sets the current record's "ioccupation" value
 * @method Profile       setLanguage1()                    Sets the current record's "language1" value
 * @method Profile       setLanguageSkill1()               Sets the current record's "language_skill1" value
 * @method Profile       setLanguage2()                    Sets the current record's "language2" value
 * @method Profile       setLanguageSkill2()               Sets the current record's "language_skill2" value
 * @method Profile       setLanguage3()                    Sets the current record's "language3" value
 * @method Profile       setLanguageSkill3()               Sets the current record's "language_skill3" value
 * @method Profile       setEducation()                    Sets the current record's "education" value
 * @method Profile       setIncome()                       Sets the current record's "income" value
 * @method Profile       setSmoker()                       Sets the current record's "smoker" value
 * @method Profile       setDrinker()                      Sets the current record's "drinker" value
 * @method Profile       setHeadline()                     Sets the current record's "headline" value
 * @method Profile       setDescription()                  Sets the current record's "description" value
 * @method Profile       setICanReceive()                  Sets the current record's "i_can_receive" value
 * @method Profile       setILookForA()                    Sets the current record's "i_look_for_a" value
 * @method Profile       setLookingForAgeFrom()            Sets the current record's "looking_for_age_from" value
 * @method Profile       setLookingForAgeTo()              Sets the current record's "looking_for_age_to" value
 * @method Profile       setLookingForAHeightFrom()        Sets the current record's "looking_for_a_height_from" value
 * @method Profile       setLookingForAHeightTo()          Sets the current record's "looking_for_a_height_to" value
 * @method Profile       setLookingForABodyTypeFrom()      Sets the current record's "looking_for_a_body_type_from" value
 * @method Profile       setLookingForABodyTypeTo()        Sets the current record's "looking_for_a_body_type_to" value
 * @method Profile       setIdealMatchDescription()        Sets the current record's "ideal_match_description" value
 * @method Profile       setNotifyMeAboutNews()            Sets the current record's "notify_me_about_news" value
 * @method Profile       setMobilePhone()                  Sets the current record's "mobile_phone" value
 * @method Profile       setPhoto()                        Sets the current record's "photo" value
 * @method Profile       setHairLenght()                   Sets the current record's "hair_lenght" value
 * @method Profile       setHairColor()                    Sets the current record's "hair_color" value
 * @method Profile       setEyeColor()                     Sets the current record's "eye_color" value
 * @method Profile       setHobbies()                      Sets the current record's "hobbies" value
 * @method Profile       setWeight()                       Sets the current record's "weight" value
 * @method Profile       setLookingFor()                   Sets the current record's "looking_for" value
 * @method Profile       setLookingForRole()               Sets the current record's "looking_for_role" value
 * @method Profile       setContactLenses()                Sets the current record's "contact_lenses" value
 * @method Profile       setIsActive()                     Sets the current record's "is_active" value
 * @method Profile       setIsNewMessage()                 Sets the current record's "is_new_message" value
 * @method Profile       setIsNewFriend()                  Sets the current record's "is_new_friend" value
 * @method Profile       setIsNewRequest()                 Sets the current record's "is_new_request" value
 * @method Profile       setIsNewGift()                    Sets the current record's "is_new_gift" value
 * @method Profile       setIsNewHotlist()                 Sets the current record's "is_new_hotlist" value
 * @method Profile       setIsEmpty()                      Sets the current record's "is_empty" value
 * @method Profile       setIsOnline()                     Sets the current record's "is_online" value
 * @method Profile       setWithPhoto()                    Sets the current record's "with_photo" value
 * @method Profile       setWithVideo()                    Sets the current record's "with_video" value
 * @method Profile       setSubtype()                      Sets the current record's "subtype" value
 * @method Profile       setMostActiveUser()               Sets the current record's "most_active_user" value
 * @method Profile       setStatusId()                     Sets the current record's "status_id" value
 * @method Profile       setHomepage()                     Sets the current record's "homepage" value
 * @method Profile       setPhone2()                       Sets the current record's "phone2" value
 * @method Profile       setIcq()                          Sets the current record's "icq" value
 * @method Profile       setMsn()                          Sets the current record's "msn" value
 * @method Profile       setSkype()                        Sets the current record's "skype" value
 * @method Profile       setZodiac()                       Sets the current record's "zodiac" value
 * @method Profile       setPartnerId()                    Sets the current record's "partner_id" value
 * @method Profile       setCanResiveGift()                Sets the current record's "can_resive_gift" value
 * @method Profile       setSkan()                         Sets the current record's "skan" value
 * @method Profile       setRating()                       Sets the current record's "rating" value
 * @method Profile       setPacketId()                     Sets the current record's "packet_id" value
 * @method Profile       setMaxAbonent()                   Sets the current record's "max_abonent" value
 * @method Profile       setCurAbonent()                   Sets the current record's "cur_abonent" value
 * @method Profile       setSubNewsletter()                Sets the current record's "sub_newsletter" value
 * @method Profile       setSubFav()                       Sets the current record's "sub_fav" value
 * @method Profile       setSubInterest()                  Sets the current record's "sub_interest" value
 * @method Profile       setSubMessage()                   Sets the current record's "sub_message" value
 * @method Profile       setCert()                         Sets the current record's "cert" value
 * @method Profile       setScamer()                       Sets the current record's "scamer" value
 * @method Profile       setIsCamera()                     Sets the current record's "is_camera" value
 * @method Profile       setIsChat()                       Sets the current record's "is_chat" value
 * @method Profile       setSendAsNew()                    Sets the current record's "send_as_new" value
 * @method Profile       setBirthdayMark()                 Sets the current record's "birthday_mark" value
 * @method Profile       setTimeOnSite()                   Sets the current record's "time_on_site" value
 * @method Profile       setIsStaff()                      Sets the current record's "is_staff" value
 * @method Profile       setIsNew()                        Sets the current record's "is_new" value
 * @method Profile       setTimenew()                      Sets the current record's "timenew" value
 * @method Profile       setIp()                           Sets the current record's "ip" value
 * @method Profile       setSfGuardUser()                  Sets the current record's "sfGuardUser" value
 * @method Profile       setStatus()                       Sets the current record's "Status" value
 * @method Profile       setPacket()                       Sets the current record's "Packet" value
 * 
 * @package    levandos
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProfile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('jo_profile');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('first_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('last_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('ifirst_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('ilast_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('middle_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('real_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('gender', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'm',
              1 => 'w',
             ),
             'default' => 'w',
             ));
        $this->hasColumn('city', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('icity', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('country', 'string', 2, array(
             'type' => 'string',
             'length' => 2,
             ));
        $this->hasColumn('zip', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('adress', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('phone', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('birthday', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('height', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('body_type', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('relationship', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('rost', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('ves', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('ethnicity', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('religion', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('marital_status', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('children', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('where_children', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('want_children', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('im', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('occupation', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('ioccupation', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('language1', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('language_skill1', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('language2', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('language_skill2', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('language3', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('language_skill3', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('education', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('income', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('smoker', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('drinker', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('headline', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('description', 'string', 25000, array(
             'type' => 'string',
             'length' => 25000,
             ));
        $this->hasColumn('i_can_receive', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('i_look_for_a', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('looking_for_age_from', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('looking_for_age_to', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('looking_for_a_height_from', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('looking_for_a_height_to', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('looking_for_a_body_type_from', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('looking_for_a_body_type_to', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('ideal_match_description', 'string', 2500, array(
             'type' => 'string',
             'length' => 2500,
             ));
        $this->hasColumn('notify_me_about_news', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('mobile_phone', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('photo', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('hair_lenght', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('hair_color', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('eye_color', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('hobbies', 'string', 2500, array(
             'type' => 'string',
             'length' => 2500,
             ));
        $this->hasColumn('weight', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('looking_for', 'string', 5, array(
             'type' => 'string',
             'length' => 5,
             ));
        $this->hasColumn('looking_for_role', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('contact_lenses', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('is_new_message', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('is_new_friend', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('is_new_request', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('is_new_gift', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('is_new_hotlist', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('is_empty', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('is_online', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('with_photo', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('with_video', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('subtype', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'none',
              1 => 'top100',
              2 => 'bikini',
             ),
             'default' => 'none',
             ));
        $this->hasColumn('most_active_user', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('status_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('homepage', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('phone2', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('icq', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('msn', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('skype', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('zodiac', 'integer', 2, array(
             'type' => 'integer',
             'length' => 2,
             ));
        $this->hasColumn('partner_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('can_resive_gift', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('skan', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('rating', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('packet_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('max_abonent', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
        $this->hasColumn('cur_abonent', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
        $this->hasColumn('sub_newsletter', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('sub_fav', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('sub_interest', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('sub_message', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('cert', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('scamer', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('is_camera', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('is_chat', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('send_as_new', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('birthday_mark', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('time_on_site', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('is_staff', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('is_new', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('timenew', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('ip', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));


        $this->index('partner_id', array(
             'fields' => 
             array(
              0 => 'partner_id',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasOne('ProfileType as Status', array(
             'local' => 'status_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('ProfilePacket as Packet', array(
             'local' => 'packet_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $cachetaggable0 = new Doctrine_Template_Cachetaggable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'description',
              1 => 'hobbies',
              2 => 'ideal_match_description',
              3 => 'ifirst_name',
              4 => 'ilast_name',
              5 => 'icity',
              6 => 'ioccupation',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($cachetaggable0);
        $this->actAs($i18n0);
    }
}