<?php

/**
 * BaseNotify
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property string $icontent
 * @property string $ititle
 * @property string $file
 * 
 * @method integer getId()       Returns the current record's "id" value
 * @method string  getTitle()    Returns the current record's "title" value
 * @method string  getIcontent() Returns the current record's "icontent" value
 * @method string  getItitle()   Returns the current record's "ititle" value
 * @method string  getFile()     Returns the current record's "file" value
 * @method Notify  setId()       Sets the current record's "id" value
 * @method Notify  setTitle()    Sets the current record's "title" value
 * @method Notify  setIcontent() Sets the current record's "icontent" value
 * @method Notify  setItitle()   Sets the current record's "ititle" value
 * @method Notify  setFile()     Sets the current record's "file" value
 * 
 * @package    levandos
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNotify extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('jo_notify');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('title', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('icontent', 'string', 100000, array(
             'type' => 'string',
             'length' => 100000,
             ));
        $this->hasColumn('ititle', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('file', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'icontent',
              1 => 'ititle',
              2 => 'file',
             ),
             ));
        $this->actAs($i18n0);
    }
}