<?php

/**
 * BaseChat2Room
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $time_start
 * @property integer $time_end
 * @property timestamp $date_start
 * @property timestamp $date_end
 * @property integer $minute
 * @property boolean $with_video
 * @property boolean $with_man_video
 * @property enum $status
 * @property integer $caller_id
 * @property integer $answer_id
 * @property integer $alert_id
 * @property integer $reject_id
 * @property boolean $accept_video
 * @property boolean $accept_man_video
 * @property boolean $accept_call_by_woman
 * @property integer $chanel_id
 * @property sfGuardUser $Caller
 * @property sfGuardUser $Answer
 * @property sfGuardUser $Alerter
 * @property sfGuardUser $Rejecter
 * @property Chat2Message $Message
 * @property Doctrine_Collection $Chat2RoomUsers
 * @property Doctrine_Collection $Chat2VideoLog
 * 
 * @method integer             getId()                   Returns the current record's "id" value
 * @method integer             getTimeStart()            Returns the current record's "time_start" value
 * @method integer             getTimeEnd()              Returns the current record's "time_end" value
 * @method timestamp           getDateStart()            Returns the current record's "date_start" value
 * @method timestamp           getDateEnd()              Returns the current record's "date_end" value
 * @method integer             getMinute()               Returns the current record's "minute" value
 * @method boolean             getWithVideo()            Returns the current record's "with_video" value
 * @method boolean             getWithManVideo()         Returns the current record's "with_man_video" value
 * @method enum                getStatus()               Returns the current record's "status" value
 * @method integer             getCallerId()             Returns the current record's "caller_id" value
 * @method integer             getAnswerId()             Returns the current record's "answer_id" value
 * @method integer             getAlertId()              Returns the current record's "alert_id" value
 * @method integer             getRejectId()             Returns the current record's "reject_id" value
 * @method boolean             getAcceptVideo()          Returns the current record's "accept_video" value
 * @method boolean             getAcceptManVideo()       Returns the current record's "accept_man_video" value
 * @method boolean             getAcceptCallByWoman()    Returns the current record's "accept_call_by_woman" value
 * @method integer             getChanelId()             Returns the current record's "chanel_id" value
 * @method sfGuardUser         getCaller()               Returns the current record's "Caller" value
 * @method sfGuardUser         getAnswer()               Returns the current record's "Answer" value
 * @method sfGuardUser         getAlerter()              Returns the current record's "Alerter" value
 * @method sfGuardUser         getRejecter()             Returns the current record's "Rejecter" value
 * @method Chat2Message        getMessage()              Returns the current record's "Message" value
 * @method Doctrine_Collection getChat2RoomUsers()       Returns the current record's "Chat2RoomUsers" collection
 * @method Doctrine_Collection getChat2VideoLog()        Returns the current record's "Chat2VideoLog" collection
 * @method Chat2Room           setId()                   Sets the current record's "id" value
 * @method Chat2Room           setTimeStart()            Sets the current record's "time_start" value
 * @method Chat2Room           setTimeEnd()              Sets the current record's "time_end" value
 * @method Chat2Room           setDateStart()            Sets the current record's "date_start" value
 * @method Chat2Room           setDateEnd()              Sets the current record's "date_end" value
 * @method Chat2Room           setMinute()               Sets the current record's "minute" value
 * @method Chat2Room           setWithVideo()            Sets the current record's "with_video" value
 * @method Chat2Room           setWithManVideo()         Sets the current record's "with_man_video" value
 * @method Chat2Room           setStatus()               Sets the current record's "status" value
 * @method Chat2Room           setCallerId()             Sets the current record's "caller_id" value
 * @method Chat2Room           setAnswerId()             Sets the current record's "answer_id" value
 * @method Chat2Room           setAlertId()              Sets the current record's "alert_id" value
 * @method Chat2Room           setRejectId()             Sets the current record's "reject_id" value
 * @method Chat2Room           setAcceptVideo()          Sets the current record's "accept_video" value
 * @method Chat2Room           setAcceptManVideo()       Sets the current record's "accept_man_video" value
 * @method Chat2Room           setAcceptCallByWoman()    Sets the current record's "accept_call_by_woman" value
 * @method Chat2Room           setChanelId()             Sets the current record's "chanel_id" value
 * @method Chat2Room           setCaller()               Sets the current record's "Caller" value
 * @method Chat2Room           setAnswer()               Sets the current record's "Answer" value
 * @method Chat2Room           setAlerter()              Sets the current record's "Alerter" value
 * @method Chat2Room           setRejecter()             Sets the current record's "Rejecter" value
 * @method Chat2Room           setMessage()              Sets the current record's "Message" value
 * @method Chat2Room           setChat2RoomUsers()       Sets the current record's "Chat2RoomUsers" collection
 * @method Chat2Room           setChat2VideoLog()        Sets the current record's "Chat2VideoLog" collection
 * 
 * @package    levandos
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseChat2Room extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('jo_chat2_room');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('time_start', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('time_end', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('date_start', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('date_end', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('minute', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('with_video', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('with_man_video', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('status', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'new',
              1 => 'wait',
              2 => 'active',
              3 => 'rejected',
              4 => 'closed',
             ),
             'default' => 'new',
             ));
        $this->hasColumn('caller_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('answer_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('alert_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('reject_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('accept_video', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('accept_man_video', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('accept_call_by_woman', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('chanel_id', 'integer', null, array(
             'type' => 'integer',
             ));


        $this->index('status', array(
             'fields' => 
             array(
              0 => 'status',
             ),
             ));
        $this->index('chanel_id', array(
             'fields' => 
             array(
              0 => 'chanel_id',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as Caller', array(
             'local' => 'caller_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser as Answer', array(
             'local' => 'answer_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser as Alerter', array(
             'local' => 'alert_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser as Rejecter', array(
             'local' => 'reject_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Chat2Message as Message', array(
             'local' => 'id',
             'foreign' => 'room_id'));

        $this->hasMany('Chat2RoomUsers', array(
             'local' => 'id',
             'foreign' => 'room_id'));

        $this->hasMany('Chat2VideoLog', array(
             'local' => 'id',
             'foreign' => 'room_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}