<?php

/**
 * BaseTypeActions
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property Doctrine_Collection $Actions
 * 
 * @method integer             getId()      Returns the current record's "id" value
 * @method string              getTitle()   Returns the current record's "title" value
 * @method Doctrine_Collection getActions() Returns the current record's "Actions" collection
 * @method TypeActions         setId()      Sets the current record's "id" value
 * @method TypeActions         setTitle()   Sets the current record's "title" value
 * @method TypeActions         setActions() Sets the current record's "Actions" collection
 * 
 * @package    levandos
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTypeActions extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('jo_type_actions');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('title', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Actions', array(
             'local' => 'id',
             'foreign' => 'type_actions_id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'title',
             ),
             ));
        $this->actAs($i18n0);
    }
}