<?php

/**
 * BaseBillingType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property string $code
 * @property integer $summa
 * @property integer $credit
 * @property Doctrine_Collection $Billing
 * 
 * @method integer             getId()      Returns the current record's "id" value
 * @method string              getTitle()   Returns the current record's "title" value
 * @method string              getCode()    Returns the current record's "code" value
 * @method integer             getSumma()   Returns the current record's "summa" value
 * @method integer             getCredit()  Returns the current record's "credit" value
 * @method Doctrine_Collection getBilling() Returns the current record's "Billing" collection
 * @method BillingType         setId()      Sets the current record's "id" value
 * @method BillingType         setTitle()   Sets the current record's "title" value
 * @method BillingType         setCode()    Sets the current record's "code" value
 * @method BillingType         setSumma()   Sets the current record's "summa" value
 * @method BillingType         setCredit()  Sets the current record's "credit" value
 * @method BillingType         setBilling() Sets the current record's "Billing" collection
 * 
 * @package    levandos
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBillingType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('jo_billing_type');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('title', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('code', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('summa', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('credit', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Billing', array(
             'local' => 'id',
             'foreign' => 'type_id'));
    }
}