<?php

/**
 * BaseStatusFriend
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property Doctrine_Collection $Friend
 * 
 * @method integer             getId()     Returns the current record's "id" value
 * @method string              getTitle()  Returns the current record's "title" value
 * @method Doctrine_Collection getFriend() Returns the current record's "Friend" collection
 * @method StatusFriend        setId()     Sets the current record's "id" value
 * @method StatusFriend        setTitle()  Sets the current record's "title" value
 * @method StatusFriend        setFriend() Sets the current record's "Friend" collection
 * 
 * @package    levandos
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStatusFriend extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('jo_status_friend');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('title', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Friend', array(
             'local' => 'id',
             'foreign' => 'status_id'));
    }
}