<?php

/**
 * BaseNewsletter
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $title
 * @property string $content
 * @property boolean $is_sent
 * @property Doctrine_Collection $Mailer
 * 
 * @method string              getName()    Returns the current record's "name" value
 * @method string              getTitle()   Returns the current record's "title" value
 * @method string              getContent() Returns the current record's "content" value
 * @method boolean             getIsSent()  Returns the current record's "is_sent" value
 * @method Doctrine_Collection getMailer()  Returns the current record's "Mailer" collection
 * @method Newsletter          setName()    Sets the current record's "name" value
 * @method Newsletter          setTitle()   Sets the current record's "title" value
 * @method Newsletter          setContent() Sets the current record's "content" value
 * @method Newsletter          setIsSent()  Sets the current record's "is_sent" value
 * @method Newsletter          setMailer()  Sets the current record's "Mailer" collection
 * 
 * @package    levandos
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNewsletter extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('jo_newsletter');
        $this->hasColumn('name', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('title', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('content', 'string', 25000, array(
             'type' => 'string',
             'length' => 25000,
             ));
        $this->hasColumn('is_sent', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Mailer', array(
             'local' => 'id',
             'foreign' => 'letter_id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'title',
              1 => 'content',
             ),
             ));
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($i18n0);
        $this->actAs($timestampable0);
    }
}