<?php

/**
 * BaseBilling
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property decimal $summa
 * @property decimal $balance
 * @property integer $credit
 * @property integer $user_id
 * @property string $username
 * @property integer $type_id
 * @property sfGuardUser $User
 * @property BillingType $BillingType
 * 
 * @method integer     getId()          Returns the current record's "id" value
 * @method string      getTitle()       Returns the current record's "title" value
 * @method decimal     getSumma()       Returns the current record's "summa" value
 * @method decimal     getBalance()     Returns the current record's "balance" value
 * @method integer     getCredit()      Returns the current record's "credit" value
 * @method integer     getUserId()      Returns the current record's "user_id" value
 * @method string      getUsername()    Returns the current record's "username" value
 * @method integer     getTypeId()      Returns the current record's "type_id" value
 * @method sfGuardUser getUser()        Returns the current record's "User" value
 * @method BillingType getBillingType() Returns the current record's "BillingType" value
 * @method Billing     setId()          Sets the current record's "id" value
 * @method Billing     setTitle()       Sets the current record's "title" value
 * @method Billing     setSumma()       Sets the current record's "summa" value
 * @method Billing     setBalance()     Sets the current record's "balance" value
 * @method Billing     setCredit()      Sets the current record's "credit" value
 * @method Billing     setUserId()      Sets the current record's "user_id" value
 * @method Billing     setUsername()    Sets the current record's "username" value
 * @method Billing     setTypeId()      Sets the current record's "type_id" value
 * @method Billing     setUser()        Sets the current record's "User" value
 * @method Billing     setBillingType() Sets the current record's "BillingType" value
 * 
 * @package    levandos
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBilling extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('jo_billing');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('title', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('summa', 'decimal', null, array(
             'type' => 'decimal',
             'scale' => 2,
             ));
        $this->hasColumn('balance', 'decimal', null, array(
             'type' => 'decimal',
             'scale' => 2,
             ));
        $this->hasColumn('credit', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('username', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('type_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('BillingType', array(
             'local' => 'type_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}