<?php

/**
 * BaseKeyword
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property integer $type_keywords_id
 * @property TypeKeywords $TypeKeywords
 * @property Doctrine_Collection $User2Keyword
 * 
 * @method integer             getId()               Returns the current record's "id" value
 * @method string              getTitle()            Returns the current record's "title" value
 * @method integer             getTypeKeywordsId()   Returns the current record's "type_keywords_id" value
 * @method TypeKeywords        getTypeKeywords()     Returns the current record's "TypeKeywords" value
 * @method Doctrine_Collection getUser2Keyword()     Returns the current record's "User2Keyword" collection
 * @method Keyword             setId()               Sets the current record's "id" value
 * @method Keyword             setTitle()            Sets the current record's "title" value
 * @method Keyword             setTypeKeywordsId()   Sets the current record's "type_keywords_id" value
 * @method Keyword             setTypeKeywords()     Sets the current record's "TypeKeywords" value
 * @method Keyword             setUser2Keyword()     Sets the current record's "User2Keyword" collection
 * 
 * @package    levandos
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseKeyword extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('keyword');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('title', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('type_keywords_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TypeKeywords', array(
             'local' => 'type_keywords_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('User2Keyword', array(
             'local' => 'id',
             'foreign' => 'keyword_id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'title',
             ),
             ));
        $this->actAs($i18n0);
    }
}