<?php

/**
 * BaseVideo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property string $username
 * @property string $title
 * @property string $file_path
 * @property boolean $pub
 * @property integer $size
 * @property string $description
 * @property string $format
 * @property boolean $is_convert
 * @property integer $partner_id
 * @property sfGuardUser $User
 * @property sfGuardUser $Partner
 * 
 * @method integer     getId()          Returns the current record's "id" value
 * @method integer     getUserId()      Returns the current record's "user_id" value
 * @method string      getUsername()    Returns the current record's "username" value
 * @method string      getTitle()       Returns the current record's "title" value
 * @method string      getFilePath()    Returns the current record's "file_path" value
 * @method boolean     getPub()         Returns the current record's "pub" value
 * @method integer     getSize()        Returns the current record's "size" value
 * @method string      getDescription() Returns the current record's "description" value
 * @method string      getFormat()      Returns the current record's "format" value
 * @method boolean     getIsConvert()   Returns the current record's "is_convert" value
 * @method integer     getPartnerId()   Returns the current record's "partner_id" value
 * @method sfGuardUser getUser()        Returns the current record's "User" value
 * @method sfGuardUser getPartner()     Returns the current record's "Partner" value
 * @method Video       setId()          Sets the current record's "id" value
 * @method Video       setUserId()      Sets the current record's "user_id" value
 * @method Video       setUsername()    Sets the current record's "username" value
 * @method Video       setTitle()       Sets the current record's "title" value
 * @method Video       setFilePath()    Sets the current record's "file_path" value
 * @method Video       setPub()         Sets the current record's "pub" value
 * @method Video       setSize()        Sets the current record's "size" value
 * @method Video       setDescription() Sets the current record's "description" value
 * @method Video       setFormat()      Sets the current record's "format" value
 * @method Video       setIsConvert()   Sets the current record's "is_convert" value
 * @method Video       setPartnerId()   Sets the current record's "partner_id" value
 * @method Video       setUser()        Sets the current record's "User" value
 * @method Video       setPartner()     Sets the current record's "Partner" value
 * 
 * @package    levandos
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVideo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('jo_video');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('username', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('title', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('file_path', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('pub', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('size', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('description', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('format', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('is_convert', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('partner_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser as Partner', array(
             'local' => 'partner_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}