<?php

/**
 * BaseSeo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $url
 * @property string $title
 * @property string $description
 * @property string $keywords
 * @property string $robots
 * @property string $revisit
 * 
 * @method integer getId()          Returns the current record's "id" value
 * @method string  getUrl()         Returns the current record's "url" value
 * @method string  getTitle()       Returns the current record's "title" value
 * @method string  getDescription() Returns the current record's "description" value
 * @method string  getKeywords()    Returns the current record's "keywords" value
 * @method string  getRobots()      Returns the current record's "robots" value
 * @method string  getRevisit()     Returns the current record's "revisit" value
 * @method Seo     setId()          Sets the current record's "id" value
 * @method Seo     setUrl()         Sets the current record's "url" value
 * @method Seo     setTitle()       Sets the current record's "title" value
 * @method Seo     setDescription() Sets the current record's "description" value
 * @method Seo     setKeywords()    Sets the current record's "keywords" value
 * @method Seo     setRobots()      Sets the current record's "robots" value
 * @method Seo     setRevisit()     Sets the current record's "revisit" value
 * 
 * @package    levandos
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSeo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('seo');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('url', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('title', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('description', 'string', 25000, array(
             'type' => 'string',
             'length' => 25000,
             ));
        $this->hasColumn('keywords', 'string', 25000, array(
             'type' => 'string',
             'length' => 25000,
             ));
        $this->hasColumn('robots', 'string', 25000, array(
             'type' => 'string',
             'length' => 25000,
             ));
        $this->hasColumn('revisit', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}