<?php

/**
 * PluginMessageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfForumMessageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginMessageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfForumMessage');
    }

    public static function getCount()
    {
        $cnt = Doctrine::getTable('sfForumMessage')->count();
        return $cnt;

    }
}