<?php

/**
 * PluginCategoryPermissionsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfForumCategoryPermissionsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginCategoryPermissionsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfForumCategoryPermissions');
    }
}