<?php

/**
 * PluginTopicTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfForumTopicTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTopicTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfForumTopic');
    }
}