<?php

/**
 * ActionsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActionsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ActionsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Actions');
    }
    
    public static function add($type,$d)
    {
        $t = TypeActionsTable::getInstance()->find($type);
        if($t)
        {
            if(sfContext::hasInstance())
            {
                if(sfContext::getInstance()->getUser()->isAuthenticated())
                {
                    $r = new Actions();
                    $r->setTypeActionsId($type);
                    $r->setUserId(sfContext::getInstance()->getUser()->getGuardUser()->getId());
                    $r->setDescription($d);
                    $r->save();
                }
            }
        }
    }
    
}