<?php

/**
 * BillingTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BillingTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BillingTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BillingType');
    }
}