<?php

/**
 * BillingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BillingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BillingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Billing');
    }
}