<?php

/**
 * Chat2RoomTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Chat2RoomTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Chat2RoomTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Chat2Room');
    }


       public static function getRoom($user)
    {
       $room = Doctrine::getTable('Chat2Room')
       ->createQuery('a')
       ->where('(a.answer_id=? or a.caller_id=?) and (a.status=? or a.status=?) ',array($user->getId(),$user->getId(),'new','active'))
       ->fetchOne();
        if($room)
        {
            return $room;

        }
        else
        {
           $room = Doctrine::getTable('Chat2Room')
           ->createQuery('a')
           ->leftJoin('a.Message m')
           ->where('(a.answer_id=? or a.caller_id=?) and m.is_read=? and a.status<>?',array($user->getId(),$user->getId(),false,'rejected'))
           ->fetchOne();
               if($room)
               {
                   return $room;
               }
            return false;
        }
    }



       public static function getAlertRoom($user)
    {
       $room = Doctrine::getTable('Chat2Room')
       ->createQuery('a')
       ->where('a.alert_id=?  and a.status=?',array($user->getId(),'wait'))
       ->fetchOne();
        if($room)
        {
            $room->setStatus('active');
            $room->save();
            return $room;

        }
        else
        {
           
            return false;
        }
    }





        
}