<?php

/**
 * Chat2RoomUsersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Chat2RoomUsersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Chat2RoomUsersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Chat2RoomUsers');
    }
}