<?php

/**
 * Chat2VideoLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Chat2VideoLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Chat2VideoLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Chat2VideoLog');
    }
}