<?php

/**
 * Chat2Room
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    levandos
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Chat2Room extends BaseChat2Room
{

    public function setStatus($v) {

       
        
        if($v=='wait')
        {
            $an = sfGuardUserTable::getInstance()->find($this->getAlertId());
            
                  if(sfConfig::get('app_use_comet')) Dklab_Realplexor::sendMessage(array(
                                'url' => 'http://'.$_SERVER['HTTP_HOST'].'/'.$an->getCulture().'/chat/call',
                                'namespace' => 'chat',
                                'chanel' => 'User_'.$this->getAlertId()
                            ));         
        }
        $this->_set('status', $v);
    }
    
    public function getAbonent($user)
    {
        if($this->caller_id == $user->getId())
        {
            return $this->getAnswer();
        }

        if($this->answer_id == $user->getId())
        {
            return $this->getCaller();
        }

    }
	
	 public function getNewMessage($user)
    {
	  $n = Doctrine::getTable('Chat2Message')->createQuery('a')->where('a.user_id=? and a.room_id=? and a.is_read=?',array($user->getId(),$this->getId(),false))->orderBy('a.timer DESC')->fetchOne();

          if($n) return $n;

          return false;

	  
	}


    public function getAllMessages()
    {
        $n = Doctrine::getTable('Chat2Message')
            ->createQuery('a')
            ->where('a.room_id=?',array($this->getId()))
            ->orderBy('a.timer DESC')
            ->execute();

     return $n;




    }



}