<?php

/**
 * Chat2MessageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Chat2MessageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Chat2MessageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Chat2Message');
    }
}