<?php

/**
 * ChatAppointmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ChatAppointmentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ChatAppointmentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ChatAppointment');
    }
    
    public static function getMyCnt($user)
    {
        $q = ChatAppointmentTable::getInstance()->createQuery('a')->where('a.man_id=?',array($user->getId()))->count();
        return $q;
    }
    
        public static function getMeCnt($user)
    {
        $q = ChatAppointmentTable::getInstance()->createQuery('a')->where('a.girl_id=?',array($user->getId()))->count();
        return $q;
    }
    
    
    
        public static function getToMeCnt($user)
    {
        $q = ChatAppointmentTable::getInstance()->createQuery('a')->where('a.girl_id=?',array($user->getId()))->count();
        return $q;
    }
    
}