<?php

/**
 * Chat2Chanels
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    levandos
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Chat2Chanels extends BaseChat2Chanels
{

    public function getStatus()
    {
        if($this->user_id>0)
        {
            return '<span style="color: red">'.__('занят').'</span>';
        }
         else {
            return '<span style="color: green">'.__('свободен').'</span>';
        }
    }

    public function delete(Doctrine_Connection $conn = null)
    {

        return true;
    }

}