<?php

/**
 * Chat2RoomUsers
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    levandos
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Chat2RoomUsers extends BaseChat2RoomUsers
{

}