<?php

/**
 * ChatAppointment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    levandos
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ChatAppointment extends BaseChatAppointment
{
    
    public function getStatusStr()
    {
        if($this->getStatus()==1)
        { 
            return __('accepted invitation');
        } elseif($this->getStatus()==2) {
            return __('refused invitation');
        } else {
            return __('new invitation');
        }
    }

        public function save(Doctrine_Connection $conn = null)
	{
                    $is_new = false;
                    if($this->isNew()) $is_new = true;


                    if($is_new)
                    {
                        $user_to = $this->getGirl();
                        $user_from = $this->getMan();
                        NotifyTable::sendTemplate($user_to,$user_from,15);
                        
                    }
                    parent::save();
        }
    
}
