<?php

/**
 * Chat2ChanelsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Chat2ChanelsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Chat2ChanelsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Chat2Chanels');
    }

    public static function getChanelByUser($user)
    {
        $c = Doctrine::getTable('Chat2Chanels')
        ->createQuery('a')
                ->where('a.user_id=?',array($user->getId()))
                ->fetchOne();
        if($c)
        {
            return $c;
        }
        else
        {
            return false;
        }

    }
}