<?php

/**
 * ContactTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContactTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContactTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Contact');
    }

    public static  function getCurrentAmmountAbonents($user)
    {

        $p = Doctrine::getTable('Contact')
            ->createQuery('a')
            ->where('a.user_id=?',array($user->getId()))
            ->count();
        return $p;
    }
}