<?php

/**
 * Faq
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    levandos
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Faq extends BaseFaq
{
    
    
        public function setPub($v) {
        if($v==true and $this->getPub()==false)
        {
            $d = 'ID:'.$this->getId();
            ActionsTable::add(7,$d);
        }
        $this->_set('pub', $v);
    }
    

}