<?php

/**
 * FaqTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FaqTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FaqTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Faq');
    }

    ////Неотвеченные
        public static function getCntNew()
    {
           $p = Doctrine::getTable('Faq')
                ->createQuery('a')
                ->where('a.pub=? and ISNULL(parent_id)',array(false))
                ->count();

            return $p;

    }

	
    ////Новые
        public static function getCntUnread($user_id)
    {
           $p = Doctrine::getTable('Faq')
                ->createQuery('a')
                ->where('a.is_read=? and user_id=?',array(false,$user_id))
                ->count();

            return $p;

    }	
	
}