<?php

/**
 * Hotlist
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    levandos
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Hotlist extends BaseHotlist
{
    public function getStatus()
    {
	    $lm = Doctrine::getTable('Message')->find($this->last_message_id);
	    if($lm)
		{
		  return $lm->getStatus();
		}
		else
		{
		  return '...';
		}
	
        if(!$this->is_opened)
        {
            return __('не откыто');
        }
        elseif($this->is_new_message)
        {
            return __('не отвечено');
        }
        else
        {
            return __('отвечено');
        }


    }

        public function save(Doctrine_Connection $conn = null)
    {
        $new = $this->isNew();
        parent::save();
        if($new)
        {
           $p = $this->getFromUser()->getProfile();
           $p->setCurAbonent($p->getCurAbonent()+1);
           $p->save();
        }
    }
}