<?php

/**
 * InterestTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InterestTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InterestTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Interest');
    }

    public static function getCnt($guard_user)
    {
        $p = Doctrine::getTable('Interest')
            ->createQuery('a')
            ->where('a.interest_id=?',array($guard_user->getId()))
            ->count();

        return $p;

    }

}