<?php

/**
 * LiqpayTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LiqpayTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LiqpayTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Liqpay');
    }
}