<?php

/**
 * MailerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MailerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MailerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Mailer');
    }


    public static function getNotify($id,$culture)
    {
        $i = Doctrine::getTable('Newsletter')
            ->createQuery('a')
            ->leftJoin('a.Translation t')
            ->where('t.id=? and t.lang=?',array($id,$culture))
            ->fetchOne();

        if($i)
        {

            return $i;
        }
        else
        {

            return false;

        }
    }

}