<?php

/**
 * MyCityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MyCityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MyCityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MyCity');
    }
}