<?php

/**
 * NewuserletterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NewuserletterTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NewuserletterTable
     */
    
     public static function createForUsers($users,$gender)
    {
        $n = new Newuserletter();
        $n->setUsersArray($users);
        $n->setToGender($gender);
        $n->save();
        return $n;
    }
    
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Newuserletter');
    }


    public static function getNewProfiles($gender)
    {
        if($gender=='man')
        {
            $g = 'w';
        }
        else
        {
            $g = 'm';
        }
        $pf = Doctrine::getTable('Profile')
            ->createQuery('a')
            ->where('a.gender=? and a.send_as_new=?',array($g, false))
            ->execute();
        
        return $pf;
    }
    
    public static function process($gender)
    {
       $users = ProfileTable::getNewUsers($gender);
       if($users)
       {
       $l = self::createForUsers($users,$gender);
       $l->setIsSend(true);
       $l->save();
       return $l;
       } else {
           return false;
       }
       
       
    }
    
}