<?php

/**
 * Newuserletter
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    levandos
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Newuserletter extends BaseNewuserletter
{



    public function setUarray($id)
    {
        $ar = explode(',',$this->getUsersArray());
        $ar[] = $id;
        $this->setUsersArray(implode(',',$ar));
        $this->save();
    }

    public function unsetUarray($id)
    {
        $ar = explode(',',$this->getUsersArray());
        unset($ar[$id]);
        $this->setUsersArray(implode(',',$ar));
        $this->save();
    }

    public function setIsSend($v)
    {
        $arrc = sfCultureInfo::getInstance('en')->getCountries();
        $this->_set('is_send', $v);

        $this->setDateSend(date('Y-m-d'));
        $this->save();

        if($v==true)
        {
            $arr = explode(',',$this->getUsersArray());
            $str = '<div style="padding-bottom: 20px; padding-left: 20px;">';
            foreach($arr as $key=>$val)
            {
                if($val>0)
                {
                    $p = Doctrine::getTable('Profile')->find($val);
                    if($p)
                    {
                        $str .= '<div style="float: left; width: 250px; height: 140px ">
                            <div style="float: left; width: 100px">
                               <a href="'.url_for('http://'.sfConfig::get('app_http_host').'/userculture/profile/show?username='.$p->getsfGuardUser()->getUsername().'&code=saltcode').'" target="_blank"><img src="http://'.sfConfig::get('app_http_host').'/'.$p->getUrlImageMiddle().'" /></a>
                            </div>
                            <div style="float: left; width: 140px">
                                  <span style="color: #BC3C03; font-size: 18px">'.$p->getFirstName().' '.$p->getLastName().'</span><br />
                                 ID: '.$p->getUserSpecId().' <br />
                                 '.$p->getCity().' <br />
                                 '.$arrc[$p->getCountry()].' <br />
                                 age '.$p->getAge().' <br />
                                 '.$p->getWeight().' kg <br />
                                 '.$p->getHeight().' cm <br />
                                 </div></div>';
                    }
                }
            }
            $str .= '<div style="clear: both"> </div></div>';

            if($this->getToGender()=='m')
            {
                $g = 'm';
            }
            else
            {
                $g = 'w';
            }

            $us = Doctrine::getTable('Profile')
                ->createQuery('a')
                ->leftJoin('a.sfGuardUser u')
                ->where('a.gender = ? and a.is_new=? and a.is_active=? and a.status_id=1 ',array($g, false, true))
                ->execute();
            foreach($us as $u)
            {
                $gu = $u->getsfGuardUser();
                if($gu)
                {
                    $strs = str_replace('saltcode',$gu->getSalt(),$str);
                    $strs = str_replace('userculture',$gu->getCulture(),$strs);


                   
                        $notice = NotifyTable::getNotify(13,$gu->getCulture());
                        $content = $notice->Translation[$gu->getCulture()]->icontent;
                        $title = $notice->Translation[$gu->getCulture()]->ititle;


                        $content = str_replace('%new_users%',$strs,$content);
                        $content = str_replace('%user_name%',$u->getFirstName().' '.$u->getLastName(),$content);
                        $content = str_replace('%login%',$gu->getUsername(),$content);
                        $content = str_replace('%password%',$gu->getPc(),$content);
                        $content = str_replace('%messagebox_link%','http://'.sfConfig::get('app_http_host').'/'.$gu->getCulture().'/message/index?code='.$gu->getSalt(),$content);
                        $content = str_replace('%contact_link%','http://'.sfConfig::get('app_http_host').'/'.$gu->getCulture().'/contact/index?code='.$gu->getSalt(),$content);



                        $m = new Mailer();
                        $m->setTitle($title);
                        $m->setContent($content);
                        $m->setEmail($gu->getEmail());
                        $m->setUserId($u->getUserId());
                        $m->save();
                    
                }
            }



        }

    }


    public function getLetter($id,$culture)
    {
        $i = Doctrine::getTable('Newuserletter')
            ->createQuery('a')
            ->leftJoin('a.Translation t')
            ->where('t.id=? and t.lang=?',array($id,$culture))
            ->fetchOne();

        if($i)
        {
            return $i;
        }
        else
        {

            return false;

        }
    }







}