<?php

/**
 * Notify
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    levandos
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Notify extends BaseNotify
{

     public function parse($arr) {

                $mes = $this->icontent;
		foreach ( $arr as $k => $v ) {
			$mes = str_replace ( $k, $v, $mes );
		}
		return $mes;
	}

     public function parse2($arr, $culture) {

                $mes = $this->Translation[$culture]->icontent;
		foreach ( $arr as $k => $v ) {
			$mes = str_replace ( $k, $v, $mes );
		}
		return $mes;
	}
        
          public function parse_title($arr, $culture) {

                $mes = $this->Translation[$culture]->ititle;
		foreach ( $arr as $k => $v ) {
			$mes = str_replace ( $k, $v, $mes );
		}
		return $mes;
	}   


        

}