<?php

/**
 * NotifyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NotifyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NotifyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Notify');
    }


    public static function getNotify($id,$culture)
    {
        $i = Doctrine::getTable('Notify')
        ->createQuery('a')
        ->leftJoin('a.Translation t')
        ->where('t.id=? and t.lang=?',array($id,$culture))
        ->fetchOne();
        
        if($i)
        {

            return $i;
        }
        else
        {
     
            return false;

        }
    }


  ///отсылка уведомления
   /// 4 - фавориты
   /// 3 - мыло
   /// 13  - интерес
  public static function sendNotify($user,$not_id,$params=array())
  {
            $profile = $user->getProfile();

           // if($not_id = 4  and !$profile->getSubFav()) return true;
           // if($not_id = 3  and !$profile->getSubMessage()) return true;
           // if($not_id = 13 and !$profile->getSubFav()) return true;


            $m = NotifyTable::getNotify($not_id, $user->getCulture());
                   if($m)
                   {
                        //// Посылаем шаблон

                       // if(strlen($m->getFile())>0)
                      //  {
                      //      $content = file_get_contents(sfConfig::get('sf_upload_dir').'/letter/'.$m->getFile());
                      //  }
                      // else
                      // {
                            $content =$m->parse2($params,$user->getCulture());
                            $title = $m->parse_title($params,$user->getCulture());
                      // }


                        //$title = $m->Translation[$user->getCulture()]->ititle;

                        mailTools::send($user->getEmail(), $title, $content);
                      // echo $not_id.'-'.$content;
                      // die;
                   }
      else
      {
        //  echo 'cccc';
        //  die;
      }

  }

    public static function sendTemplate($guard_user_to,$guard_user_from,$not_id)
    {
     //   $o = Doctrine::getTable('Notify')->find($not_id);
     //   $guard_user = Doctrine::getTable('sfGuardUser')->find($user_id);
     //   if($culture=='null')
     //   $culture = $guard_user->getCulture();
     //   $m = NotifyTable::getNotify($not_id,$culture);
     //   $title = $m->Translation[$culture]->ititle;
     //   $contents = $m->Translation[$culture]->icontent;

       // $filename = sfConfig::get('sf_upload_dir').'/letter/'.$o->getFile();
      //  $handle = fopen($filename, "r");
      //  $contents = fread($handle, filesize($filename));
      //  fclose($handle);
       // echo $guard_user_to->getProfile()->getUserId();
      //  die;

        /*  %member_link%
         *  %favorite_link%
         * %gallery_link%
         * %myprofile_link%
         * %messagebox_link%
         * %userprofile_link%
         * %membearea_link%
         * %contact_link%
         *  %age_user%
         *  %city_user%
         *  %user_name%
         *
         *
         *
         */
          $arrc = sfCultureInfo::getInstance($guard_user_to->getCulture())->getCountries();

                $par = array(
                '%background_url%' =>'http://'.$_SERVER['HTTP_HOST'].'/img/bgl.jpg',
                '%button_url%' => 'http://'.$_SERVER['HTTP_HOST'].'/img/lbutton.jpg',
                '%header_image%' => 'http://'.$_SERVER['HTTP_HOST'].'/img/header.jpg',
                '%image_link%' => 'http://'.$_SERVER['HTTP_HOST'].'/'.$guard_user_from->getProfile()->getUrlImage(),
                '%user_name%' =>  $guard_user_from->getProfile()->getFirstName().' '.$guard_user_from->getProfile()->getLastName(),
                '%gallery_link%' => 'http://'.$_SERVER['HTTP_HOST'].'/'.$guard_user_to->getCulture().'/search/index?code='.$guard_user_to->getSalt(),
                '%member_link%' => 'http://'.$_SERVER['HTTP_HOST'].'/'.$guard_user_to->getCulture().'/profile/member?code='.$guard_user_to->getSalt(),
                '%favorite_link%' => 'http://'.$_SERVER['HTTP_HOST'].'/'.$guard_user_to->getCulture().'/friend/index?code='.$guard_user_to->getSalt(),
                '%myprofile_link%' => 'http://'.$_SERVER['HTTP_HOST'].'/'.$guard_user_to->getCulture().'/profile/my?code='.$guard_user_to->getSalt(),
                '%messagebox_link%' => 'http://'.$_SERVER['HTTP_HOST'].'/'.$guard_user_to->getCulture().'/message/index?code='.$guard_user_to->getSalt(),
                '%userprofile_link%' => 'http://'.$_SERVER['HTTP_HOST'].'/'.$guard_user_to->getCulture().'/profile/show?username='.$guard_user_from->getUsername().'&code='.$guard_user_to->getSalt(),
                '%contact_link%' => 'http://'.$_SERVER['HTTP_HOST'].'/'.$guard_user_to->getCulture().'/contact/index?code='.$guard_user_to->getSalt(),
                '%age_user%' => $guard_user_from->getProfile()->getAge(),
                '%city_user%' => $guard_user_from->getProfile()->getCity(),
                '%id_user%' => $guard_user_from->getProfile()->getUserSpecId(),
                '%login%' => $guard_user_to->getUsername(),
                '%password%' => $guard_user_to->getPc(),
                '%country_user%' => $arrc[$guard_user_from->getProfile()->getCountry()]
            );


           if($not_id==13)
           {

               if($guard_user_to->getGender()=='m')
               {
                   $gender = 'w';
               }
               else{
                   $gender = 'm';
               }

               $str = '<div>';
               $users = Doctrine::getTable('sfGuardUser')
                   ->createQuery('a')
                   ->where('a.gender=? and a.is_active=?',array($gender,true))
                   ->orderBy('a.id DESC')
                   ->limit(20)
                   ->execute();
               foreach($users as $u)
               {
                   $p = $u->getProfile();
                   if($p)

                   $str .= '<div style="float: left; font-size: 12px; width: 270px; height: 160px"><table>
                              <tr>
                                <td valign="top">
                                  <a href="'.'http://'.$_SERVER['HTTP_HOST'].'/'.$guard_user_to->getCulture().'/profile/show?username='.$u->getUsername().'&code='.$u->getSalt().'"><img src="'.'http://'.$_SERVER['HTTP_HOST'].'/'.$u->getProfile()->getUrlImageMiddle().'"></a>
                                </td>
                                <td  valign="top">
                                   <table>
                                       <tr>
                                         <td colspan="2"><a href="'.'http://'.$_SERVER['HTTP_HOST'].'/'.$guard_user_to->getCulture().'/profile/show?username='.$u->getUsername().'&code='.$u->getSalt().'">'.$p->getFirstName().' '.$p->getLastName().'</a></td>
                                       </tr>
                                       <tr>
                                         <td> ID: </td>
                                         <td>'.$p->getUserSpecId().'</td>
                                       </tr>
                                        <tr>
                                         <td> City: </td>
                                         <td> '.$p->getCity().'</td>
                                       </tr>
                                        <tr>
                                         <td> Country: </td>
                                         <td> '.$arrc[$p->getCountry()].' </td>
                                       </tr>
                                        <tr>
                                         <td> Age: </td>
                                         <td> '.$p->getAge() .' </td>
                                       </tr>
                                        <tr>
                                         <td> Higth: </td>
                                         <td> '.$p->getHeight().' sm. </td>
                                       </tr>
                                        <tr>
                                         <td> Weight: </td>
                                         <td> '.$p->getWeight() .' kg.</td>
                                       </tr>
                                   </table>
                                </td>
                              </tr>
                            </table></div>';

               }
               $str .= '</div>';
               $par['%new_users%'] = $str;
           }

        NotifyTable::sendNotify($guard_user_to, $not_id, $par);



        //mailTools::send($guard_user->getEmail(), $title, $contents);
        return true;
    }





    public static function sendTemplateBatch($guard_user_to,$guard_user_from,$not_id)
    {

        $arrc = sfCultureInfo::getInstance($guard_user_to->getCulture())->getCountries();
        $host = 'www.our-feeling.com';
        $par = array(
            '%background_url%' =>'http://'.$host.'/img/bgl.jpg',
            '%button_url%' => 'http://'.$host.'/img/lbutton.jpg',
            '%header_image%' => 'http://'.$host.'/img/header.jpg',
            '%image_link%' => 'http://'.$host.'/'.$guard_user_from->getProfile()->getUrlImage(),
            '%user_name%' =>  $guard_user_from->getProfile()->getFirstName().' '.$guard_user_from->getProfile()->getLastName(),
            '%gallery_link%' => 'http://'.$host.'/'.$guard_user_to->getCulture().'/search/index?code='.$guard_user_to->getSalt(),
            '%member_link%' => 'http://'.$host.'/'.$guard_user_to->getCulture().'/profile/member?code='.$guard_user_to->getSalt(),
            '%favorite_link%' => 'http://'.$host.'/'.$guard_user_to->getCulture().'/friend/index?code='.$guard_user_to->getSalt(),
            '%myprofile_link%' => 'http://'.$host.'/'.$guard_user_to->getCulture().'/profile/my?code='.$guard_user_to->getSalt(),
            '%messagebox_link%' => 'http://'.$host.'/'.$guard_user_to->getCulture().'/message/index?code='.$guard_user_to->getSalt(),
            '%userprofile_link%' => 'http://'.$host.'/'.$guard_user_to->getCulture().'/profile/show?username='.$guard_user_from->getUsername().'&code='.$guard_user_to->getSalt(),
            '%contact_link%' => 'http://'.$host.'/'.$guard_user_to->getCulture().'/contact/index?code='.$guard_user_to->getSalt(),
            '%age_user%' => $guard_user_from->getProfile()->getAge(),
            '%city_user%' => $guard_user_from->getProfile()->getCity(),
            '%id_user%' => $guard_user_from->getProfile()->getUserSpecId(),
            '%login%' => $guard_user_to->getUsername(),
            '%password%' => $guard_user_to->getPc(),
            '%country_user%' => $arrc[$guard_user_from->getProfile()->getCountry()]
        );


        if($not_id==13)
        {

            if($guard_user_to->getGender()=='m')
            {
                $gender = 'w';
            }
            else{
                $gender = 'm';
            }

            $str = '<div>';
            $users = Doctrine::getTable('sfGuardUser')
                ->createQuery('a')
                ->where('a.gender=? and a.is_active=?',array($gender,true))
                ->orderBy('a.id DESC')
                ->limit(20)
                ->execute();
            foreach($users as $u)
            {
                $p = $u->getProfile();
                if($p)

                    $str .= '<div style="float: left; font-size: 12px; width: 270px; height: 160px"><table>
                              <tr>
                                <td valign="top">
                                  <a href="'.'http://'.$_SERVER['HTTP_HOST'].'/'.$host.'/profile/show?username='.$u->getUsername().'&code='.$u->getSalt().'"><img src="'.'http://'.$_SERVER['HTTP_HOST'].'/'.$u->getProfile()->getUrlImageMiddle().'"></a>
                                </td>
                                <td  valign="top">
                                   <table>
                                       <tr>
                                         <td colspan="2"><a href="'.'http://'.$host.'/'.$guard_user_to->getCulture().'/profile/show?username='.$u->getUsername().'&code='.$u->getSalt().'">'.$p->getFirstName().' '.$p->getLastName().'</a></td>
                                       </tr>
                                       <tr>
                                         <td> ID: </td>
                                         <td>'.$p->getUserSpecId().'</td>
                                       </tr>
                                        <tr>
                                         <td> City: </td>
                                         <td> '.$p->getCity().'</td>
                                       </tr>
                                        <tr>
                                         <td> Country: </td>
                                         <td> '.$arrc[$p->getCountry()].' </td>
                                       </tr>
                                        <tr>
                                         <td> Age: </td>
                                         <td> '.$p->getAge() .' </td>
                                       </tr>
                                        <tr>
                                         <td> Higth: </td>
                                         <td> '.$p->getHeight().' sm. </td>
                                       </tr>
                                        <tr>
                                         <td> Weight: </td>
                                         <td> '.$p->getWeight() .' kg.</td>
                                       </tr>
                                   </table>
                                </td>
                              </tr>
                            </table></div>';

            }
            $str .= '</div>';
            $par['%new_users%'] = $str;
        }

        NotifyTable::sendNotify($guard_user_to, $not_id, $par);



        //mailTools::send($guard_user->getEmail(), $title, $contents);
        return true;
    }



}