<?php

/**
 * Payment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    levandos
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Payment extends BasePayment
{

         public function setUserId($value)
    {
        $this->_set('user_id', $value);
        $s = Doctrine::getTable('sfGuardUser')->find($value);
        if($s)
        $this->setUsername($s->getUsername());

    }



}