<?php

/**
 * ProfilePacket
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    levandos
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ProfilePacket extends BaseProfilePacket
{

    public function getSumma()
    {
        if($this->getId()==1) return 0;
        return 100;
    }
    
}