<?php

/**
 * ProfileTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfileTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProfileTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProfileType');
    }
}