<?php

/**
 * ProfilePacketTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfilePacketTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProfilePacketTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProfilePacket');
    }
}