<?php

/**
 * ScamerReportTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ScamerReportTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ScamerReportTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ScamerReport');
    }
}