<?php

/**
 * SeoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SeoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SeoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Seo');
    }
}