<?php

/**
 * Settings
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    levandos
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Settings extends BaseSettings
{

     public function save(Doctrine_Connection $conn = null)
    {

         parent::save();
         $this->makeSetting();
         $this->clearCache();

    }

    private function clearCache()
    {
        sfToolkit::clearDirectory(sfConfig::get('sf_cache_dir'));
    }


        private function makeSetting()
    {
       $str = '';    
       $it = Doctrine::getTable('Settings')->findAll();
       foreach($it as $i)
       {
           $str .= '  '.$i->getVarName().': '.$i->getVarValue()."\n";
       }

       $fp = fopen (sfConfig::get('sf_config_dir').'/inc/settings.yml', "w");
       fwrite ($fp, $str);
       fclose ($fp);



    }


}