<?php

/**
 * StatusFriendTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StatusFriendTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StatusFriendTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StatusFriend');
    }
}