<?php

/**
 * SuggestionsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SuggestionsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SuggestionsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Suggestions');
    }
}