<?php

/**
 * TypeActionsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TypeActionsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TypeActionsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TypeActions');
    }
}