<?php

/**
 * User2KeywordTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class User2KeywordTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object User2KeywordTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('User2Keyword');
    }
}