<?php

/**
 * Video
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    levandos
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Video extends BaseVideo
{

     public function delete(Doctrine_Connection $conn = null)
    {
            $f = sfConfig::get('sf_upload_dir').'/video/'.$this->getFilePath();
            @unlink($f);
            $f = sfConfig::get('sf_upload_dir').'/video/'.$this->getFilePath().'.flv';
            @unlink($f);
	    $f = sfConfig::get('sf_upload_dir').'/video/thumbnail/'.$this->getFilePath().'.jpeg';
            @unlink($f);
         $user = $this->getUser();
         NotifyTable::sendNotify($user, 6);
         parent::delete();

    }





    public function save(Doctrine_Connection $conn = null)
	{


          parent::save();
          ////Устанавливаем флаг с видео
             $cnt = Doctrine::getTable('Video')
             ->createQuery('a')
             ->where('a.user_id=? and a.pub=?',array($this->user_id,true))
             ->count();

             if($cnt>0)
             {

                 $pr = ProfileTable::getProfileById($this->getUserId());
                 if($pr)
                 {
                     $pr->setWithVideo(true);
                     $pr->save();
                 }
             }




	}




}