<?php

/**
 * ViewedTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ViewedTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ViewedTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Viewed');
    }


    public static function getCnt($guard_user)
    {
        $p = Doctrine::getTable('Viewed')
            ->createQuery('a')
            ->where('a.interest_id=?',array($guard_user->getId()))
            ->count();

        return $p;

    }

}