<?php
define('DB_HOST', 'localhost');
define('DB_USER', 'zdimon_buh_test');
define('DB_PASSWORD','1qa2ws3ed4rf');
define('DB_NAME', 'buh_nauka_new');
define('DB_TYPE', 'mysql');
define('SITE_URL', 'http://www.buh-nauka.com/');
define('SITE_URI', 'www.buh-nauka.com');
define('SMARTY_PATH', MAIN_PATH.'/lib/smarty/');

////////////////Постраничка
define('DOSKA_PER_PAGE', '15');
define('DOSKA_PER_LIST', '15');
define('CONTENT_PER_PAGE', '20');
define('CONTENT_PER_LIST', '25');
define('SEARCH_PER_PAGE', '15');
define('SEARCH_PER_LIST', '15');
define('MONITORING_PER_PAGE', '50');
define('MONITORING_PER_LIST', '50');
define('USERS_PER_PAGE', '20');
define('USERS_PER_LIST', '20');
define('FAQ_PER_PAGE', '10');
define('FAQ_PER_LIST', '10');
define('CONS_PER_PAGE', '15');
define('CONS_PER_LIST', '15');
///////////////////////////


///////////////
define('SIZE_SMALL_FOTO', '149');
define('UPLOAD_FOTO_PATH', 'upl_img/');
define('UPLOAD_FOTO_PATH_URL', 'http://www.buh-nauka.com');
define('UPLOAD_FOTO_PATH_ABS', '/sata1/home/users/buhnauka/www/www.buh-nauka.com/upl_img/');
define('PREVIEW_FOTO_PATH_DOSKA', 'upl_img/doska/_');

///////////////


///////////
define('ID_ACCESS', '7');
define('ID_CONS', '13');
define('ID_EDU', '20');
define('COST_CLICK', '5');
define('DEBUG_DB', '0');
define('SITE_ALIAS', 'uk');
define('DB_PREFIX', '');
define('TIME_ONLINE', '1000');
//////////



?>