<?php

/**
 * sfForumProfileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfForumProfileTable extends PluginsfForumProfileTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfForumProfileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfForumProfile');
    }
}