<?php

/**
 * sfForumCategoryPermissionsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfForumCategoryPermissionsTable extends PluginsfForumCategoryPermissionsTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfForumCategoryPermissionsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfForumCategoryPermissions');
    }
}