<?php

/**
 * sfForumCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfForumCategoryTable extends PluginsfForumCategoryTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfForumCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfForumCategory');
    }
}