<?php

/**
 * sfForumTopicTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfForumTopicTable extends PluginsfForumTopicTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfForumTopicTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfForumTopic');
    }
}